var namespaces =
[
    [ "AgentProvider", "namespace_agent_provider.html", "namespace_agent_provider" ],
    [ "", null, null ],
    [ "AgentSystemManagement", "namespace_agent_system_management.html", "namespace_agent_system_management" ],
    [ "AIClientFacade", "namespace_a_i_client_facade.html", "namespace_a_i_client_facade" ],
    [ "AIRunner", "namespace_a_i_runner.html", "namespace_a_i_runner" ],
    [ "Enumeration", "namespace_enumeration.html", null ],
    [ "EnvironmentPluginAPI", "namespace_environment_plugin_a_p_i.html", "namespace_environment_plugin_a_p_i" ],
    [ "", null, null ],
    [ "Exceptions", "namespace_exceptions.html", null ],
    [ "Export", "namespace_export.html", null ],
    [ "FactoryGame", "namespace_factory_game.html", "namespace_factory_game" ],
    [ "", null, null ],
    [ "", null, null ],
    [ "GameServerFacade", "namespace_game_server_facade.html", "namespace_game_server_facade" ],
    [ "GameStatistics", "namespace_game_statistics.html", "namespace_game_statistics" ],
    [ "Interfaces", "namespace_interfaces.html", null ],
    [ "", null, null ],
    [ "", null, null ],
    [ "", null, null ],
    [ "", null, null ],
    [ "", null, null ],
    [ "", null, null ],
    [ "", null, null ],
    [ "OverseerGUI", "namespace_overseer_g_u_i.html", null ],
    [ "PluginAPI", "namespace_plugin_a_p_i.html", "namespace_plugin_a_p_i" ],
    [ "RemoteInterface", "namespace_remote_interface.html", null ],
    [ "ServerRunner", "namespace_server_runner.html", "namespace_server_runner" ],
    [ "Settings", "namespace_settings.html", null ],
    [ "SimpleFactoryPlayer", "namespace_simple_factory_player.html", "namespace_simple_factory_player" ],
    [ "TransportTypes", "namespace_transport_types.html", null ],
    [ "", null, null ]
];