var namespace_environment_plugin_a_p_i_1_1_contract_1_1_exception =
[
    [ "CorruptMapFileException", "class_environment_plugin_a_p_i_1_1_contract_1_1_exception_1_1_corrupt_map_file_exception.html", "class_environment_plugin_a_p_i_1_1_contract_1_1_exception_1_1_corrupt_map_file_exception" ],
    [ "IllegalActionException", "class_environment_plugin_a_p_i_1_1_contract_1_1_exception_1_1_illegal_action_exception.html", "class_environment_plugin_a_p_i_1_1_contract_1_1_exception_1_1_illegal_action_exception" ],
    [ "IllegalNumberOfClientsException", "class_environment_plugin_a_p_i_1_1_contract_1_1_exception_1_1_illegal_number_of_clients_exception.html", "class_environment_plugin_a_p_i_1_1_contract_1_1_exception_1_1_illegal_number_of_clients_exception" ],
    [ "TechnicalException", "class_environment_plugin_a_p_i_1_1_contract_1_1_exception_1_1_technical_exception.html", "class_environment_plugin_a_p_i_1_1_contract_1_1_exception_1_1_technical_exception" ]
];