var searchData=
[
  ['validationexception',['ValidationException',['../classorg_1_1hibernate_1_1metamodel_1_1_validation_exception.html',1,'org::hibernate::metamodel']]],
  ['validationremark',['ValidationRemark',['../classorg_1_1h2_1_1jaqu_1_1_validation_remark.html',1,'org::h2::jaqu']]],
  ['validationtest',['ValidationTest',['../classorg_1_1junit_1_1tests_1_1validation_1_1_validation_test.html',1,'org::junit::tests::validation']]],
  ['validityauditstrategy',['ValidityAuditStrategy',['../classorg_1_1hibernate_1_1envers_1_1strategy_1_1_validity_audit_strategy.html',1,'org::hibernate::envers::strategy']]],
  ['validityauditstrategymanytomanytest',['ValidityAuditStrategyManyToManyTest',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1strategy_1_1_validity_audit_strategy_many_to_many_test.html',1,'org::hibernate::envers::test::integration::strategy']]],
  ['validityauditstrategyrevendtestcustomrevent',['ValidityAuditStrategyRevEndTestCustomRevEnt',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1strategy_1_1_validity_audit_strategy_rev_end_test_custom_rev_ent.html',1,'org::hibernate::envers::test::integration::strategy']]],
  ['validityauditstrategyrevendtstest',['ValidityAuditStrategyRevEndTsTest',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1strategy_1_1_validity_audit_strategy_rev_end_ts_test.html',1,'org::hibernate::envers::test::integration::strategy']]],
  ['validtimeauditstrategy',['ValidTimeAuditStrategy',['../classorg_1_1hibernate_1_1envers_1_1strategy_1_1_valid_time_audit_strategy.html',1,'org::hibernate::envers::strategy']]],
  ['value',['Value',['../classorg_1_1h2_1_1test_1_1synth_1_1sql_1_1_value.html',1,'org::h2::test::synth::sql']]],
  ['value',['Value',['../classorg_1_1h2_1_1value_1_1_value.html',1,'org::h2::value']]],
  ['value',['Value',['../classorg_1_1hibernate_1_1test_1_1component_1_1cascading_1_1collection_1_1_value.html',1,'org::hibernate::test::component::cascading::collection']]],
  ['value',['Value',['../interfaceorg_1_1hibernate_1_1mapping_1_1_value.html',1,'org::hibernate::mapping']]],
  ['value',['Value',['../interfaceorg_1_1hibernate_1_1metamodel_1_1relational_1_1_value.html',1,'org::hibernate::metamodel::relational']]],
  ['value_3c_20accesstype_20_3e',['Value&lt; AccessType &gt;',['../interfaceorg_1_1hibernate_1_1metamodel_1_1relational_1_1_value.html',1,'org::hibernate::metamodel::relational']]],
  ['value_3c_20class_3c_3f_3e_20_3e',['Value&lt; Class&lt;?&gt; &gt;',['../interfaceorg_1_1hibernate_1_1metamodel_1_1relational_1_1_value.html',1,'org::hibernate::metamodel::relational']]],
  ['value_3c_20classloaderservice_20_3e',['Value&lt; ClassLoaderService &gt;',['../interfaceorg_1_1hibernate_1_1metamodel_1_1relational_1_1_value.html',1,'org::hibernate::metamodel::relational']]],
  ['value_3c_20persisterclassresolver_20_3e',['Value&lt; PersisterClassResolver &gt;',['../interfaceorg_1_1hibernate_1_1metamodel_1_1relational_1_1_value.html',1,'org::hibernate::metamodel::relational']]],
  ['value_3c_20t_20_3e',['Value&lt; T &gt;',['../classorg_1_1hibernate_1_1internal_1_1util_1_1_value_3_01_t_01_4.html',1,'org::hibernate::internal::util']]],
  ['valuearray',['ValueArray',['../classorg_1_1h2_1_1value_1_1_value_array.html',1,'org::h2::value']]],
  ['valuebinder_3c_20x_20_3e',['ValueBinder&lt; X &gt;',['../interfaceorg_1_1hibernate_1_1type_1_1descriptor_1_1_value_binder_3_01_x_01_4.html',1,'org::hibernate::type::descriptor']]],
  ['valueblob',['ValueBlob',['../interfaceorg_1_1h2_1_1value_1_1_value_1_1_value_blob.html',1,'org::h2::value::Value']]],
  ['valueboolean',['ValueBoolean',['../classorg_1_1h2_1_1value_1_1_value_boolean.html',1,'org::h2::value']]],
  ['valuebyte',['ValueByte',['../classorg_1_1h2_1_1value_1_1_value_byte.html',1,'org::h2::value']]],
  ['valuebytes',['ValueBytes',['../classorg_1_1h2_1_1value_1_1_value_bytes.html',1,'org::h2::value']]],
  ['valueclassification',['ValueClassification',['../enumorg_1_1hibernate_1_1ejb_1_1metamodel_1_1_attribute_factory_1_1_value_context_1_1_value_classification.html',1,'org::hibernate::ejb::metamodel::AttributeFactory::ValueContext']]],
  ['valueclob',['ValueClob',['../interfaceorg_1_1h2_1_1value_1_1_value_1_1_value_clob.html',1,'org::h2::value::Value']]],
  ['valuecontainer',['ValueContainer',['../interfaceorg_1_1hibernate_1_1metamodel_1_1relational_1_1_value_container.html',1,'org::hibernate::metamodel::relational']]],
  ['valuedannotation',['ValuedAnnotation',['../interfaceorg_1_1junit_1_1tests_1_1description_1_1_annotated_description_test_1_1_valued_annotation.html',1,'org::junit::tests::description::AnnotatedDescriptionTest']]],
  ['valuedate',['ValueDate',['../classorg_1_1h2_1_1value_1_1_value_date.html',1,'org::h2::value']]],
  ['valuedecimal',['ValueDecimal',['../classorg_1_1h2_1_1value_1_1_value_decimal.html',1,'org::h2::value']]],
  ['valuedouble',['ValueDouble',['../classorg_1_1h2_1_1value_1_1_value_double.html',1,'org::h2::value']]],
  ['valueexpression',['ValueExpression',['../classorg_1_1h2_1_1expression_1_1_value_expression.html',1,'org::h2::expression']]],
  ['valueextractor_3c_20x_20_3e',['ValueExtractor&lt; X &gt;',['../interfaceorg_1_1hibernate_1_1type_1_1descriptor_1_1_value_extractor_3_01_x_01_4.html',1,'org::hibernate::type::descriptor']]],
  ['valuefloat',['ValueFloat',['../classorg_1_1h2_1_1value_1_1_value_float.html',1,'org::h2::value']]],
  ['valuehandlerfactory',['ValueHandlerFactory',['../classorg_1_1hibernate_1_1ejb_1_1criteria_1_1_value_handler_factory.html',1,'org::hibernate::ejb::criteria']]],
  ['valuehashmap_3c_20v_20_3e',['ValueHashMap&lt; V &gt;',['../classorg_1_1h2_1_1util_1_1_value_hash_map_3_01_v_01_4.html',1,'org::h2::util']]],
  ['valueinclusion',['ValueInclusion',['../enumorg_1_1hibernate_1_1engine_1_1spi_1_1_value_inclusion.html',1,'org::hibernate::engine::spi']]],
  ['valueint',['ValueInt',['../classorg_1_1h2_1_1value_1_1_value_int.html',1,'org::h2::value']]],
  ['valuejavaobject',['ValueJavaObject',['../classorg_1_1h2_1_1value_1_1_value_java_object.html',1,'org::h2::value']]],
  ['valuelob',['ValueLob',['../classorg_1_1h2_1_1value_1_1_value_lob.html',1,'org::h2::value']]],
  ['valuelobdb',['ValueLobDb',['../classorg_1_1h2_1_1value_1_1_value_lob_db.html',1,'org::h2::value']]],
  ['valuelong',['ValueLong',['../classorg_1_1h2_1_1value_1_1_value_long.html',1,'org::h2::value']]],
  ['valuenull',['ValueNull',['../classorg_1_1h2_1_1value_1_1_value_null.html',1,'org::h2::value']]],
  ['valuerelationalstate',['ValueRelationalState',['../interfaceorg_1_1hibernate_1_1metamodel_1_1relational_1_1state_1_1_value_relational_state.html',1,'org::hibernate::metamodel::relational::state']]],
  ['valueresultset',['ValueResultSet',['../classorg_1_1h2_1_1value_1_1_value_result_set.html',1,'org::h2::value']]],
  ['valuesbagcollectioneventtest',['ValuesBagCollectionEventTest',['../classorg_1_1hibernate_1_1test_1_1event_1_1collection_1_1values_1_1_values_bag_collection_event_test.html',1,'org::hibernate::test::event::collection::values']]],
  ['valueshort',['ValueShort',['../classorg_1_1h2_1_1value_1_1_value_short.html',1,'org::h2::value']]],
  ['valuestring',['ValueString',['../classorg_1_1h2_1_1value_1_1_value_string.html',1,'org::h2::value']]],
  ['valuestringfixed',['ValueStringFixed',['../classorg_1_1h2_1_1value_1_1_value_string_fixed.html',1,'org::h2::value']]],
  ['valuestringignorecase',['ValueStringIgnoreCase',['../classorg_1_1h2_1_1value_1_1_value_string_ignore_case.html',1,'org::h2::value']]],
  ['valuetime',['ValueTime',['../classorg_1_1h2_1_1value_1_1_value_time.html',1,'org::h2::value']]],
  ['valuetimestamp',['ValueTimestamp',['../classorg_1_1h2_1_1value_1_1_value_timestamp.html',1,'org::h2::value']]],
  ['valueuuid',['ValueUuid',['../classorg_1_1h2_1_1value_1_1_value_uuid.html',1,'org::h2::value']]],
  ['valuevisitor',['ValueVisitor',['../interfaceorg_1_1hibernate_1_1mapping_1_1_value_visitor.html',1,'org::hibernate::mapping']]],
  ['valuevisitortest',['ValueVisitorTest',['../classorg_1_1hibernate_1_1test_1_1mapping_1_1_value_visitor_test.html',1,'org::hibernate::test::mapping']]],
  ['vanillaswap',['VanillaSwap',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1embedded_1_1_vanilla_swap.html',1,'org::hibernate::test::annotations::embedded']]],
  ['varargssqlfunction',['VarArgsSQLFunction',['../classorg_1_1hibernate_1_1dialect_1_1function_1_1_var_args_s_q_l_function.html',1,'org::hibernate::dialect::function']]],
  ['varbinarytypedescriptor',['VarbinaryTypeDescriptor',['../classorg_1_1hibernate_1_1type_1_1descriptor_1_1sql_1_1_varbinary_type_descriptor.html',1,'org::hibernate::type::descriptor::sql']]],
  ['varchartypedescriptor',['VarcharTypeDescriptor',['../classorg_1_1hibernate_1_1type_1_1descriptor_1_1sql_1_1_varchar_type_descriptor.html',1,'org::hibernate::type::descriptor::sql']]],
  ['variable',['Variable',['../classorg_1_1h2_1_1jaqu_1_1bytecode_1_1_variable.html',1,'org::h2::jaqu::bytecode']]],
  ['variable',['Variable',['../classorg_1_1h2_1_1expression_1_1_variable.html',1,'org::h2::expression']]],
  ['variouskeywordpropertyentity',['VariousKeywordPropertyEntity',['../classorg_1_1hibernate_1_1test_1_1hql_1_1_various_keyword_property_entity.html',1,'org::hibernate::test::hql']]],
  ['varioustypesentity',['VariousTypesEntity',['../classorg_1_1hibernate_1_1test_1_1typedescriptor_1_1_various_types_entity.html',1,'org::hibernate::test::typedescriptor']]],
  ['vegetable',['Vegetable',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1inheritance_1_1_vegetable.html',1,'org::hibernate::test::annotations::inheritance']]],
  ['vegetablepk',['VegetablePk',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1inheritance_1_1_vegetable_pk.html',1,'org::hibernate::test::annotations::inheritance']]],
  ['vehicle',['Vehicle',['../classorg_1_1hibernate_1_1test_1_1entityname_1_1_vehicle.html',1,'org::hibernate::test::entityname']]],
  ['vehicle',['Vehicle',['../classorg_1_1hibernate_1_1test_1_1cascade_1_1circle_1_1_vehicle.html',1,'org::hibernate::test::cascade::circle']]],
  ['vehicle',['Vehicle',['../classorg_1_1hibernate_1_1test_1_1hql_1_1_vehicle.html',1,'org::hibernate::test::hql']]],
  ['vehicule',['Vehicule',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1various_1_1_vehicule.html',1,'org::hibernate::test::annotations::various']]],
  ['vendor',['Vendor',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoone_1_1referencedcolumnname_1_1_vendor.html',1,'org::hibernate::test::annotations::manytoone::referencedcolumnname']]],
  ['vendor',['Vendor',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1referencedcolumnname_1_1_vendor.html',1,'org::hibernate::test::annotations::referencedcolumnname']]],
  ['verifierruletest',['VerifierRuleTest',['../classorg_1_1junit_1_1tests_1_1experimental_1_1rules_1_1_verifier_rule_test.html',1,'org::junit::tests::experimental::rules']]],
  ['verifyfetchprofilereferencesecondpass',['VerifyFetchProfileReferenceSecondPass',['../classorg_1_1hibernate_1_1cfg_1_1_verify_fetch_profile_reference_second_pass.html',1,'org::hibernate::cfg']]],
  ['version',['Version',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1defaultpar_1_1_version.html',1,'org::hibernate::ejb::test::pack::defaultpar']]],
  ['version',['Version',['../classorg_1_1hibernate_1_1test_1_1schemaupdate_1_1_version.html',1,'org::hibernate::test::schemaupdate']]],
  ['version',['Version',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1war_1_1_version.html',1,'org::hibernate::ejb::test::pack::war']]],
  ['version',['Version',['../classorg_1_1hibernate_1_1_version.html',1,'org::hibernate']]],
  ['version',['Version',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1indexcoll_1_1_version.html',1,'org::hibernate::test::annotations::indexcoll']]],
  ['version1',['Version1',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1defaultpar__1__0_1_1_version1.html',1,'org::hibernate::ejb::test::pack::defaultpar_1_0']]],
  ['versionedbook',['VersionedBook',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1lob_1_1_versioned_book.html',1,'org::hibernate::test::annotations::lob']]],
  ['versionedcompiledcode',['VersionedCompiledCode',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1lob_1_1_versioned_compiled_code.html',1,'org::hibernate::test::annotations::lob']]],
  ['versionedentity',['VersionedEntity',['../classorg_1_1hibernate_1_1test_1_1nonflushedchanges_1_1_versioned_entity.html',1,'org::hibernate::test::nonflushedchanges']]],
  ['versionedentity',['VersionedEntity',['../classorg_1_1hibernate_1_1ejb_1_1metamodel_1_1_versioned_entity.html',1,'org::hibernate::ejb::metamodel']]],
  ['versionedentity',['VersionedEntity',['../classorg_1_1hibernate_1_1test_1_1ops_1_1_versioned_entity.html',1,'org::hibernate::test::ops']]],
  ['versionedentitywithinversemanytomanytest',['VersionedEntityWithInverseManyToManyTest',['../classorg_1_1hibernate_1_1test_1_1immutable_1_1entitywithmutablecollection_1_1inverse_1_1_versionbb05e91c790e3efad11f0aa4e3a00274.html',1,'org::hibernate::test::immutable::entitywithmutablecollection::inverse']]],
  ['versionedentitywithinverseonetomanyfailureexpectedtest',['VersionedEntityWithInverseOneToManyFailureExpectedTest',['../classorg_1_1hibernate_1_1test_1_1immutable_1_1entitywithmutablecollection_1_1inverse_1_1_version35cb2db21bce59fc6df9f2e989b37ee9.html',1,'org::hibernate::test::immutable::entitywithmutablecollection::inverse']]],
  ['versionedentitywithinverseonetomanyjointest',['VersionedEntityWithInverseOneToManyJoinTest',['../classorg_1_1hibernate_1_1test_1_1immutable_1_1entitywithmutablecollection_1_1inverse_1_1_versionce177a5891d9256f0f75350e89bee149.html',1,'org::hibernate::test::immutable::entitywithmutablecollection::inverse']]],
  ['versionedentitywithinverseonetomanytest',['VersionedEntityWithInverseOneToManyTest',['../classorg_1_1hibernate_1_1test_1_1immutable_1_1entitywithmutablecollection_1_1inverse_1_1_versionda248cf228c7e9817d9359c8239c8789.html',1,'org::hibernate::test::immutable::entitywithmutablecollection::inverse']]],
  ['versionedentitywithnoninversemanytomanytest',['VersionedEntityWithNonInverseManyToManyTest',['../classorg_1_1hibernate_1_1test_1_1immutable_1_1entitywithmutablecollection_1_1noninverse_1_1_vers2b7aa2a6270a27be6f907a096c1263eb.html',1,'org::hibernate::test::immutable::entitywithmutablecollection::noninverse']]],
  ['versionedentitywithnoninverseonetomanyjointest',['VersionedEntityWithNonInverseOneToManyJoinTest',['../classorg_1_1hibernate_1_1test_1_1immutable_1_1entitywithmutablecollection_1_1noninverse_1_1_versa513c18b8fd95471cb6b7ad98c5e906e.html',1,'org::hibernate::test::immutable::entitywithmutablecollection::noninverse']]],
  ['versionedentitywithnoninverseonetomanytest',['VersionedEntityWithNonInverseOneToManyTest',['../classorg_1_1hibernate_1_1test_1_1immutable_1_1entitywithmutablecollection_1_1noninverse_1_1_verscaa0a671e76fd89a585741f20d0673e9.html',1,'org::hibernate::test::immutable::entitywithmutablecollection::noninverse']]],
  ['versioneditem',['VersionedItem',['../classorg_1_1hibernate_1_1test_1_1cache_1_1infinispan_1_1functional_1_1_versioned_item.html',1,'org::hibernate::test::cache::infinispan::functional']]],
  ['versioneditem',['VersionedItem',['../classorg_1_1hibernate_1_1test_1_1cache_1_1ehcache_1_1_versioned_item.html',1,'org::hibernate::test::cache::ehcache']]],
  ['versioneditem',['VersionedItem',['../classorg_1_1hibernate_1_1test_1_1domain_1_1_versioned_item.html',1,'org::hibernate::test::domain']]],
  ['versionedlobtest',['VersionedLobTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1lob_1_1_versioned_lob_test.html',1,'org::hibernate::test::annotations::lob']]],
  ['versionednode',['VersionedNode',['../classorg_1_1hibernate_1_1test_1_1readonly_1_1_versioned_node.html',1,'org::hibernate::test::readonly']]],
  ['versioning',['Versioning',['../classorg_1_1hibernate_1_1engine_1_1internal_1_1_versioning.html',1,'org::hibernate::engine::internal']]],
  ['versionproperty',['VersionProperty',['../classorg_1_1hibernate_1_1tuple_1_1_version_property.html',1,'org::hibernate::tuple']]],
  ['versionsjointablenaming',['VersionsJoinTableNaming',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1_versions_join_table_naming.html',1,'org::hibernate::envers::test::integration::naming']]],
  ['versionsjointablerangecomponent_3c_20t_20extends_20versionsjointablerangetestentitysuperclass_20_3e',['VersionsJoinTableRangeComponent&lt; T extends VersionsJoinTableRangeTestEntitySuperClass &gt;',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1_versions_join_table_range_c92f36281b7a4618cbb193aff4f45777b.html',1,'org::hibernate::envers::test::integration::naming']]],
  ['versionsjointablerangecomponentnamingtest',['VersionsJoinTableRangeComponentNamingTest',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1_versions_join_table_range_component_naming_test.html',1,'org::hibernate::envers::test::integration::naming']]],
  ['versionsjointablerangecomponenttestentity',['VersionsJoinTableRangeComponentTestEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1_versions_join_table_range_component_test_entity.html',1,'org::hibernate::envers::test::integration::naming']]],
  ['versionsjointablerangetestalternateentity',['VersionsJoinTableRangeTestAlternateEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1_versions_join_table_range_test_alternate_entity.html',1,'org::hibernate::envers::test::integration::naming']]],
  ['versionsjointablerangetestentity',['VersionsJoinTableRangeTestEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1_versions_join_table_range_test_entity.html',1,'org::hibernate::envers::test::integration::naming']]],
  ['versionsjointablerangetestentitysuperclass',['VersionsJoinTableRangeTestEntitySuperClass',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1_versions_join_table_range_test_entity_super_class.html',1,'org::hibernate::envers::test::integration::naming']]],
  ['versionsjointabletestentity',['VersionsJoinTableTestEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1_versions_join_table_test_entity.html',1,'org::hibernate::envers::test::integration::naming']]],
  ['versionsproperties',['VersionsProperties',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1properties_1_1_versions_properties.html',1,'org::hibernate::envers::test::integration::properties']]],
  ['versiontest',['VersionTest',['../classorg_1_1hibernate_1_1test_1_1version_1_1_version_test.html',1,'org::hibernate::test::version']]],
  ['versiontype_3c_20t_20_3e',['VersionType&lt; T &gt;',['../interfaceorg_1_1hibernate_1_1type_1_1_version_type_3_01_t_01_4.html',1,'org::hibernate::type']]],
  ['versiontypeseedparameterspecification',['VersionTypeSeedParameterSpecification',['../classorg_1_1hibernate_1_1param_1_1_version_type_seed_parameter_specification.html',1,'org::hibernate::param']]],
  ['versionvalue',['VersionValue',['../classorg_1_1hibernate_1_1engine_1_1spi_1_1_version_value.html',1,'org::hibernate::engine::spi']]],
  ['vertex_3c_20r_20_3e',['Vertex&lt; R &gt;',['../classorg_1_1hibernate_1_1envers_1_1tools_1_1graph_1_1_vertex_3_01_r_01_4.html',1,'org::hibernate::envers::tools::graph']]],
  ['veryslowtests',['VerySlowTests',['../interfaceorg_1_1junit_1_1tests_1_1experimental_1_1categories_1_1_category_test_1_1_very_slow_tests.html',1,'org::junit::tests::experimental::categories::CategoryTest']]],
  ['vetoer',['Vetoer',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_vetoer.html',1,'org::hibernate::test::legacy']]],
  ['vicepresident',['VicePresident',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1xml_1_1ejb3_1_1_vice_president.html',1,'org::hibernate::test::annotations::xml::ejb3']]],
  ['videosystem',['VideoSystem',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1callbacks_1_1_video_system.html',1,'org::hibernate::ejb::test::callbacks']]],
  ['viewcursor',['ViewCursor',['../classorg_1_1h2_1_1index_1_1_view_cursor.html',1,'org::h2::index']]],
  ['viewindex',['ViewIndex',['../classorg_1_1h2_1_1index_1_1_view_index.html',1,'org::h2::index']]],
  ['violatedconstraintnameextracter',['ViolatedConstraintNameExtracter',['../interfaceorg_1_1hibernate_1_1exception_1_1spi_1_1_violated_constraint_name_extracter.html',1,'org::hibernate::exception::spi']]],
  ['vmtimestamped',['VMTimestamped',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1various_1_1_v_m_timestamped.html',1,'org::hibernate::test::annotations::various']]],
  ['voice',['Voice',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1entitynonentity_1_1_voice.html',1,'org::hibernate::test::annotations::entitynonentity']]],
  ['vtihelper',['VTIHelper',['../classorg_1_1apache_1_1derby_demo_1_1vtis_1_1core_1_1_v_t_i_helper.html',1,'org::apache::derbyDemo::vtis::core']]],
  ['vtis',['VTIs',['../classorg_1_1apache_1_1derby_demo_1_1vtis_1_1example_1_1_v_t_is.html',1,'org::apache::derbyDemo::vtis::example']]],
  ['vtitemplate',['VTITemplate',['../classorg_1_1apache_1_1derby_demo_1_1vtis_1_1core_1_1_v_t_i_template.html',1,'org::apache::derbyDemo::vtis::core']]]
];
