var searchData=
[
  ['m2mindexedlistnotauditedtarget',['M2MIndexedListNotAuditedTarget',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1manytomany_1_1unidirectional_1_1_m2_m_indexed_list_not_audited_target.html',1,'org::hibernate::envers::test::integration::manytomany::unidirectional']]],
  ['m2mindexedlisttargetnotauditedentity',['M2MIndexedListTargetNotAuditedEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1manytomany_1_1unidirectional_1_1_m2_m_inda33ddac353fee476a917fd6c81822500.html',1,'org::hibernate::envers::test::entities::manytomany::unidirectional']]],
  ['m2mrelationnotauditedtarget',['M2MRelationNotAuditedTarget',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1manytomany_1_1unidirectional_1_1_m2_m_relation_not_audited_target.html',1,'org::hibernate::envers::test::integration::manytomany::unidirectional']]],
  ['m2mtargetnotauditedentity',['M2MTargetNotAuditedEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1manytomany_1_1unidirectional_1_1_m2_m_target_not_audited_entity.html',1,'org::hibernate::envers::test::entities::manytomany::unidirectional']]],
  ['machine',['Machine',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1tableperclass_1_1_machine.html',1,'org::hibernate::test::annotations::tableperclass']]],
  ['mail',['Mail',['../classorg_1_1hibernate_1_1test_1_1orphan_1_1_mail.html',1,'org::hibernate::test::orphan']]],
  ['mail',['Mail',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1emops_1_1_mail.html',1,'org::hibernate::ejb::test::emops']]],
  ['mainentity',['MainEntity',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1annotations_1_1entity_1_1_embeddable_binding_test_1_1_main_entity.html',1,'org::hibernate::metamodel::source::annotations::entity::EmbeddableBindingTest']]],
  ['mainobject',['MainObject',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_main_object.html',1,'org::hibernate::test::legacy']]],
  ['maintest',['MainTest',['../classorg_1_1joda_1_1time_1_1chrono_1_1gj_1_1_main_test.html',1,'org::joda::time::chrono::gj']]],
  ['mammal',['Mammal',['../classorg_1_1hibernate_1_1test_1_1hql_1_1_mammal.html',1,'org::hibernate::test::hql']]],
  ['mammal',['Mammal',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1ops_1_1_mammal.html',1,'org::hibernate::ejb::test::ops']]],
  ['mammal',['Mammal',['../classorg_1_1hibernate_1_1test_1_1collection_1_1original_1_1_mammal.html',1,'org::hibernate::test::collection::original']]],
  ['man',['Man',['../classorg_1_1hibernate_1_1test_1_1criteria_1_1_man.html',1,'org::hibernate::test::criteria']]],
  ['man',['Man',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytomany_1_1_man.html',1,'org::hibernate::test::annotations::manytomany']]],
  ['manageable',['Manageable',['../interfaceorg_1_1hibernate_1_1service_1_1spi_1_1_manageable.html',1,'org::hibernate::service::spi']]],
  ['manageddevice',['ManagedDevice',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1onetoone_1_1hhh4851_1_1_managed_device.html',1,'org::hibernate::test::annotations::onetoone::hhh4851']]],
  ['manageddrivingtest',['ManagedDrivingTest',['../classorg_1_1hibernate_1_1test_1_1transaction_1_1jta_1_1_managed_driving_test.html',1,'org::hibernate::test::transaction::jta']]],
  ['managedflushchecker',['ManagedFlushChecker',['../interfaceorg_1_1hibernate_1_1engine_1_1transaction_1_1synchronization_1_1spi_1_1_managed_flush_checker.html',1,'org::hibernate::engine::transaction::synchronization::spi']]],
  ['managedobject',['ManagedObject',['../classorg_1_1hibernate_1_1test_1_1propertyref_1_1cachedcollections_1_1_managed_object.html',1,'org::hibernate::test::propertyref::cachedcollections']]],
  ['managedsessioncontext',['ManagedSessionContext',['../classorg_1_1hibernate_1_1context_1_1internal_1_1_managed_session_context.html',1,'org::hibernate::context::internal']]],
  ['manager',['Manager',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1embedded_1_1_manager.html',1,'org::hibernate::test::annotations::embedded']]],
  ['manpk',['ManPk',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytomany_1_1_man_pk.html',1,'org::hibernate::test::annotations::manytomany']]],
  ['manualflush',['ManualFlush',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1flush_1_1_manual_flush.html',1,'org::hibernate::envers::test::integration::flush']]],
  ['manualflushautocommitdisabled',['ManualFlushAutoCommitDisabled',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1flush_1_1_manual_flush_auto_commit_disabled.html',1,'org::hibernate::envers::test::integration::flush']]],
  ['manufacturer',['Manufacturer',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoonewithformula_1_1_manufacturer.html',1,'org::hibernate::test::annotations::manytoonewithformula']]],
  ['manufacturer',['Manufacturer',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1xml_1_1ejb3_1_1_manufacturer.html',1,'org::hibernate::test::annotations::xml::ejb3']]],
  ['manufacturer',['Manufacturer',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1onetomany_1_1_manufacturer.html',1,'org::hibernate::test::annotations::onetomany']]],
  ['manufacturerid',['ManufacturerId',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoonewithformula_1_1_manufacturer_id.html',1,'org::hibernate::test::annotations::manytoonewithformula']]],
  ['many',['Many',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_many.html',1,'org::hibernate::test::legacy']]],
  ['manyoperationsintransaction',['ManyOperationsInTransaction',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1basic_1_1_many_operations_in_transaction.html',1,'org::hibernate::envers::test::integration::basic']]],
  ['manytoany',['ManyToAny',['../interfaceorg_1_1hibernate_1_1annotations_1_1_many_to_any.html',1,'org::hibernate::annotations']]],
  ['manytoanycollectionelement',['ManyToAnyCollectionElement',['../classorg_1_1hibernate_1_1metamodel_1_1binding_1_1_many_to_any_collection_element.html',1,'org::hibernate::metamodel::binding']]],
  ['manytoanypluralattributeelementsource',['ManyToAnyPluralAttributeElementSource',['../interfaceorg_1_1hibernate_1_1metamodel_1_1source_1_1binder_1_1_many_to_any_plural_attribute_element_source.html',1,'org::hibernate::metamodel::source::binder']]],
  ['manytomanyassociationclassassignedidtest',['ManyToManyAssociationClassAssignedIdTest',['../classorg_1_1hibernate_1_1test_1_1manytomanyassociationclass_1_1surrogateid_1_1assigned_1_1_many_6c2c6ba8231c5bd456d26b428d87cfeb.html',1,'org::hibernate::test::manytomanyassociationclass::surrogateid::assigned']]],
  ['manytomanyassociationclasscompositeidtest',['ManyToManyAssociationClassCompositeIdTest',['../classorg_1_1hibernate_1_1test_1_1manytomanyassociationclass_1_1compositeid_1_1_many_to_many_association_class_composite_id_test.html',1,'org::hibernate::test::manytomanyassociationclass::compositeid']]],
  ['manytomanyassociationclassgeneratedidtest',['ManyToManyAssociationClassGeneratedIdTest',['../classorg_1_1hibernate_1_1test_1_1manytomanyassociationclass_1_1surrogateid_1_1generated_1_1_manya57f834d26312a2b593bb29cdfdb2a1d.html',1,'org::hibernate::test::manytomanyassociationclass::surrogateid::generated']]],
  ['manytomanycollectionelement',['ManyToManyCollectionElement',['../classorg_1_1hibernate_1_1metamodel_1_1binding_1_1_many_to_many_collection_element.html',1,'org::hibernate::metamodel::binding']]],
  ['manytomanyinversetosuperclasstest',['ManyToManyInverseToSuperclassTest',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1manytomany_1_1inverse_to_superclass_1_d92bab4d57285a8d92963e1b650df9a6.html',1,'org::hibernate::envers::test::integration::manytomany::inverseToSuperclass']]],
  ['manytomanymaxfetchdepth0test',['ManyToManyMaxFetchDepth0Test',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytomany_1_1_many_to_many_max_fetch_depth0_test.html',1,'org::hibernate::test::annotations::manytomany']]],
  ['manytomanypluralattributeelementsource',['ManyToManyPluralAttributeElementSource',['../interfaceorg_1_1hibernate_1_1metamodel_1_1source_1_1binder_1_1_many_to_many_plural_attribute_element_source.html',1,'org::hibernate::metamodel::source::binder']]],
  ['manytomanypluralattributeelementsourceimpl',['ManyToManyPluralAttributeElementSourceImpl',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1hbm_1_1_many_to_many_plural_attribute_element_source_impl.html',1,'org::hibernate::metamodel::source::hbm']]],
  ['manytomanytest',['ManyToManyTest',['../classorg_1_1hibernate_1_1test_1_1manytomany_1_1_many_to_many_test.html',1,'org::hibernate::test::manytomany']]],
  ['manytomanytest',['ManyToManyTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytomany_1_1_many_to_many_test.html',1,'org::hibernate::test::annotations::manytomany']]],
  ['manytoone',['ManyToOne',['../classorg_1_1hibernate_1_1mapping_1_1_many_to_one.html',1,'org::hibernate::mapping']]],
  ['manytooneattributebinding',['ManyToOneAttributeBinding',['../classorg_1_1hibernate_1_1metamodel_1_1binding_1_1_many_to_one_attribute_binding.html',1,'org::hibernate::metamodel::binding']]],
  ['manytoonecomponent',['ManyToOneComponent',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1components_1_1relations_1_1_many_to_one_component.html',1,'org::hibernate::envers::test::entities::components::relations']]],
  ['manytoonecomponenttestentity',['ManyToOneComponentTestEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1components_1_1relations_1_1_many_to_one_component_test_entity.html',1,'org::hibernate::envers::test::entities::components::relations']]],
  ['manytooneentity',['ManyToOneEntity',['../classorg_1_1hibernate_1_1metamodel_1_1binding_1_1_many_to_one_entity.html',1,'org::hibernate::metamodel::binding']]],
  ['manytooneidnotaudited',['ManyToOneIdNotAudited',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1ids_1_1_many_to_one_id_not_audited.html',1,'org::hibernate::envers::test::integration::ids']]],
  ['manytooneidnotauditedtestentity',['ManyToOneIdNotAuditedTestEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1ids_1_1_many_to_one_id_not_audited_test_entity.html',1,'org::hibernate::envers::test::entities::ids']]],
  ['manytooneincomponent',['ManyToOneInComponent',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1components_1_1relations_1_1_many_to_one_in_component.html',1,'org::hibernate::envers::test::integration::components::relations']]],
  ['manytoonejointest',['ManyToOneJoinTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoone_1_1_many_to_one_join_test.html',1,'org::hibernate::test::annotations::manytoone']]],
  ['manytoonenotauditedembid',['ManyToOneNotAuditedEmbId',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1ids_1_1_many_to_one_not_audited_emb_id.html',1,'org::hibernate::envers::test::entities::ids']]],
  ['manytoonenotinsertable',['ManyToOneNotInsertable',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1notinsertable_1_1manytoone_1_1_many_to_one_not_insertable.html',1,'org::hibernate::envers::test::integration::notinsertable::manytoone']]],
  ['manytoonenotinsertableentity',['ManyToOneNotInsertableEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1notinsertable_1_1manytoone_1_1_many_to_one_not_insertable_entity.html',1,'org::hibernate::envers::test::integration::notinsertable::manytoone']]],
  ['manytooneowning',['ManyToOneOwning',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1manytoone_1_1bidirectional_1_1_many_to_one_owning.html',1,'org::hibernate::envers::test::integration::manytoone::bidirectional']]],
  ['manytoonereferencedcolumnnametest',['ManyToOneReferencedColumnNameTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoone_1_1referencedcolumnname_1_1_many_to_one_referenced_column_name_test.html',1,'org::hibernate::test::annotations::manytoone::referencedcolumnname']]],
  ['manytoonerelationalstate',['ManyToOneRelationalState',['../interfaceorg_1_1hibernate_1_1metamodel_1_1relational_1_1state_1_1_many_to_one_relational_state.html',1,'org::hibernate::metamodel::relational::state']]],
  ['manytoonetest',['ManyToOneTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoone_1_1_many_to_one_test.html',1,'org::hibernate::test::annotations::manytoone']]],
  ['manytoonetype',['ManyToOneType',['../classorg_1_1hibernate_1_1type_1_1_many_to_one_type.html',1,'org::hibernate::type']]],
  ['manytoonewithformulatest',['ManyToOneWithFormulaTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoonewithformula_1_1_many_to_one_with_formula_test.html',1,'org::hibernate::test::annotations::manytoonewithformula']]],
  ['map',['Map',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20class_3c_3f_3e_2c_20embeddabletypeimpl_3c_3f_3e_20_3e',['Map&lt; Class&lt;?&gt;, EmbeddableTypeImpl&lt;?&gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20class_3c_3f_3e_2c_20entitytypeimpl_3c_3f_3e_20_3e',['Map&lt; Class&lt;?&gt;, EntityTypeImpl&lt;?&gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20class_3c_3f_3e_2c_20org_2ehibernate_2emapping_2emappedsuperclass_20_3e',['Map&lt; Class&lt;?&gt;, org.hibernate.mapping.MappedSuperclass &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20extendsqueueentry_2c_3f_3e',['Map&lt; ExtendsQueueEntry,?&gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20integer_2c_20string_20_3e',['Map&lt; Integer, String &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20mappedsuperclass_2c_20mappedsuperclasstypeimpl_3c_3f_3e_20_3e',['Map&lt; MappedSuperclass, MappedSuperclassTypeImpl&lt;?&gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20mappedsuperclasstypeimpl_3c_3f_3e_2c_20persistentclass_20_3e',['Map&lt; MappedSuperclassTypeImpl&lt;?&gt;, PersistentClass &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20persistentclass_2c_20entitytypeimpl_3c_3f_3e_20_3e',['Map&lt; PersistentClass, EntityTypeImpl&lt;?&gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20annotatedclasstype_20_3e',['Map&lt; String, AnnotatedClassType &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20anymetadef_20_3e',['Map&lt; String, AnyMetaDef &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20attribute_3c_20x_2c_3f_3e_20_3e',['Map&lt; String, Attribute&lt; X,?&gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20collection_20_3e',['Map&lt; String, Collection &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20column_5b_5d_3e',['Map&lt; String, Column[]&gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20entitytypeimpl_3c_3f_3e_20_3e',['Map&lt; String, EntityTypeImpl&lt;?&gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20fetchprofile_20_3e',['Map&lt; String, FetchProfile &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20filterdefinition_20_3e',['Map&lt; String, FilterDefinition &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20idgenerator_20_3e',['Map&lt; String, IdGenerator &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20join_20_3e',['Map&lt; String, Join &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20joincolumn_5b_5d_3e',['Map&lt; String, JoinColumn[]&gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20jointable_20_3e',['Map&lt; String, JoinTable &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20map_3c_20string_2c_20join_20_3e_20_3e',['Map&lt; String, Map&lt; String, Join &gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20namedquerydefinition_20_3e',['Map&lt; String, NamedQueryDefinition &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20namedsqlquerydefinition_20_3e',['Map&lt; String, NamedSQLQueryDefinition &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20persistentclass_20_3e',['Map&lt; String, PersistentClass &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20pluralattribute_3c_20x_2c_3f_2c_3f_3e_20_3e',['Map&lt; String, PluralAttribute&lt; X,?,?&gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20properties_20_3e',['Map&lt; String, Properties &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20resultsetmappingdefinition_20_3e',['Map&lt; String, ResultSetMappingDefinition &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20singularattribute_3c_20x_2c_3f_3e_20_3e',['Map&lt; String, SingularAttribute&lt; X,?&gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20sqlfunction_20_3e',['Map&lt; String, SQLFunction &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20string_20_3e',['Map&lt; String, String &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20table_20_3e',['Map&lt; String, Table &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20typedef_20_3e',['Map&lt; String, TypeDef &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20xclass_20_3e',['Map&lt; String, XClass &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20string_2c_20xmldocument_20_3e',['Map&lt; String, XmlDocument &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20table_2c_20list_3c_20uniqueconstraintholder_20_3e_20_3e',['Map&lt; Table, List&lt; UniqueConstraintHolder &gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20xclass_2c_20inheritancestate_20_3e',['Map&lt; XClass, InheritanceState &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['map_3c_20xclass_2c_20map_3c_20string_2c_20propertydata_20_3e_20_3e',['Map&lt; XClass, Map&lt; String, PropertyData &gt; &gt;',['../classorg_1_1hibernate_1_1mapping_1_1_map.html',1,'org::hibernate::mapping']]],
  ['mapaccessor',['MapAccessor',['../classorg_1_1hibernate_1_1property_1_1_map_accessor.html',1,'org::hibernate::property']]],
  ['mapattributejoin_3c_20o_2c_20k_2c_20v_20_3e',['MapAttributeJoin&lt; O, K, V &gt;',['../classorg_1_1hibernate_1_1ejb_1_1criteria_1_1path_1_1_map_attribute_join_3_01_o_00_01_k_00_01_v_01_4.html',1,'org::hibernate::ejb::criteria::path']]],
  ['mapbinder',['MapBinder',['../classorg_1_1hibernate_1_1cfg_1_1annotations_1_1_map_binder.html',1,'org::hibernate::cfg::annotations']]],
  ['mapcollectioninitializor_3c_20t_20extends_20map_20_3e',['MapCollectionInitializor&lt; T extends Map &gt;',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1lazy_1_1initializor_1_1_map9458ce7706749ae8a2f1f3e98c6107e8.html',1,'org::hibernate::envers::entities::mapper::relation::lazy::initializor']]],
  ['mapcollectionmapper_3c_20t_20extends_20map_20_3e',['MapCollectionMapper&lt; T extends Map &gt;',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1_map_collection_mapper_3_01_t_01extends_01_map_01_4.html',1,'org::hibernate::envers::entities::mapper::relation']]],
  ['mapcompositeelementtest',['MapCompositeElementTest',['../classorg_1_1hibernate_1_1test_1_1mapcompelem_1_1_map_composite_element_test.html',1,'org::hibernate::test::mapcompelem']]],
  ['mapelementformulatest',['MapElementFormulaTest',['../classorg_1_1hibernate_1_1test_1_1mapelemformula_1_1_map_element_formula_test.html',1,'org::hibernate::test::mapelemformula']]],
  ['mapentryexpression_3c_20k_2c_20v_20_3e',['MapEntryExpression&lt; K, V &gt;',['../classorg_1_1hibernate_1_1ejb_1_1criteria_1_1expression_1_1_map_entry_expression_3_01_k_00_01_v_01_4.html',1,'org::hibernate::ejb::criteria::expression']]],
  ['mapentrynode',['MapEntryNode',['../classorg_1_1hibernate_1_1hql_1_1internal_1_1ast_1_1tree_1_1_map_entry_node.html',1,'org::hibernate::hql::internal::ast::tree']]],
  ['mapindexformulatest',['MapIndexFormulaTest',['../classorg_1_1hibernate_1_1test_1_1map_1_1_map_index_formula_test.html',1,'org::hibernate::test::map']]],
  ['mapjoinimplementor_3c_20z_2c_20k_2c_20v_20_3e',['MapJoinImplementor&lt; Z, K, V &gt;',['../interfaceorg_1_1hibernate_1_1ejb_1_1criteria_1_1_map_join_implementor_3_01_z_00_01_k_00_01_v_01_4.html',1,'org::hibernate::ejb::criteria']]],
  ['mapkey',['MapKey',['../classorg_1_1hibernate_1_1test_1_1collection_1_1backref_1_1map_1_1compkey_1_1_map_key.html',1,'org::hibernate::test::collection::backref::map::compkey']]],
  ['mapkeycolumndelegator',['MapKeyColumnDelegator',['../classorg_1_1hibernate_1_1cfg_1_1annotations_1_1_map_key_column_delegator.html',1,'org::hibernate::cfg::annotations']]],
  ['mapkeyhelpers',['MapKeyHelpers',['../classorg_1_1hibernate_1_1ejb_1_1criteria_1_1path_1_1_map_key_helpers.html',1,'org::hibernate::ejb::criteria::path']]],
  ['mapkeyjoincolumndelegator',['MapKeyJoinColumnDelegator',['../classorg_1_1hibernate_1_1cfg_1_1annotations_1_1_map_key_join_column_delegator.html',1,'org::hibernate::cfg::annotations']]],
  ['mapkeynode',['MapKeyNode',['../classorg_1_1hibernate_1_1hql_1_1internal_1_1ast_1_1tree_1_1_map_key_node.html',1,'org::hibernate::hql::internal::ast::tree']]],
  ['mapkeytest',['MapKeyTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1indexcoll_1_1_map_key_test.html',1,'org::hibernate::test::annotations::indexcoll']]],
  ['mapkeytype',['MapKeyType',['../interfaceorg_1_1hibernate_1_1annotations_1_1_map_key_type.html',1,'org::hibernate::annotations']]],
  ['maplazyinitializer',['MapLazyInitializer',['../classorg_1_1hibernate_1_1proxy_1_1map_1_1_map_lazy_initializer.html',1,'org::hibernate::proxy::map']]],
  ['maplisttablemodel',['MapListTableModel',['../class_models_1_1_map_list_table_model.html',1,'Models']]],
  ['mapownedentity',['MapOwnedEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1manytomany_1_1_map_owned_entity.html',1,'org::hibernate::envers::test::entities::manytomany']]],
  ['mapowningentity',['MapOwningEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1manytomany_1_1_map_owning_entity.html',1,'org::hibernate::envers::test::entities::manytomany']]],
  ['mappedattribute',['MappedAttribute',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1annotations_1_1attribute_1_1_mapped_attribute.html',1,'org::hibernate::metamodel::source::annotations::attribute']]],
  ['mappedgrandparententity',['MappedGrandparentEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1superclass_1_1auditparents_1_1_mapped_grandparent_entity.html',1,'org::hibernate::envers::test::integration::superclass::auditparents']]],
  ['mappedparententity',['MappedParentEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1superclass_1_1auditparents_1_1_mapped_parent_entity.html',1,'org::hibernate::envers::test::integration::superclass::auditparents']]],
  ['mappedsuperclass',['MappedSuperclass',['../classorg_1_1hibernate_1_1mapping_1_1_mapped_superclass.html',1,'org::hibernate::mapping']]],
  ['mappedsuperclasstest',['MappedSuperclassTest',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1annotations_1_1entity_1_1_mapped_superclass_test.html',1,'org::hibernate::metamodel::source::annotations::entity']]],
  ['mappedsuperclasstypeimpl_3c_20x_20_3e',['MappedSuperclassTypeImpl&lt; X &gt;',['../classorg_1_1hibernate_1_1ejb_1_1metamodel_1_1_mapped_superclass_type_impl_3_01_x_01_4.html',1,'org::hibernate::ejb::metamodel']]],
  ['mappedsuperclasswithattributestest',['MappedSuperclassWithAttributesTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1metagen_1_1mappedsuperclass_1_1attribute_1_1_mapped_superclass_with_attributes_test.html',1,'org::hibernate::ejb::test::metagen::mappedsuperclass::attribute']]],
  ['mappedsuperclasswithembeddedidtest',['MappedSuperclassWithEmbeddedIdTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1metagen_1_1mappedsuperclass_1_1embeddedid_1_1_mapped_superclass_with_embedded_id_test.html',1,'org::hibernate::ejb::test::metagen::mappedsuperclass::embeddedid']]],
  ['mappedsuperclasswithembeddedtest',['MappedSuperclassWithEmbeddedTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1metagen_1_1mappedsuperclass_1_1embedded_1_1_mapped_superclass_with_embedded_test.html',1,'org::hibernate::ejb::test::metagen::mappedsuperclass::embedded']]],
  ['mappedsuperclasswithentitywithidclasstest',['MappedSuperclassWithEntityWithIdClassTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1metagen_1_1mappedsuperclass_1_1idclass_1_1_mapped_superca758286dcf4097e1aa42d339afe1d179.html',1,'org::hibernate::ejb::test::metagen::mappedsuperclass::idclass']]],
  ['mapping',['Mapping',['../interfaceorg_1_1hibernate_1_1engine_1_1spi_1_1_mapping.html',1,'org::hibernate::engine::spi']]],
  ['mappingdefaults',['MappingDefaults',['../interfaceorg_1_1hibernate_1_1metamodel_1_1source_1_1_mapping_defaults.html',1,'org::hibernate::metamodel::source']]],
  ['mappingdocument',['MappingDocument',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1hbm_1_1_mapping_document.html',1,'org::hibernate::metamodel::source::hbm']]],
  ['mappingexception',['MappingException',['../classorg_1_1hibernate_1_1_mapping_exception.html',1,'org::hibernate']]],
  ['mappingexception',['MappingException',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1_mapping_exception.html',1,'org::hibernate::metamodel::source']]],
  ['mappingexceptiontest',['MappingExceptionTest',['../classorg_1_1hibernate_1_1test_1_1mappingexception_1_1_mapping_exception_test.html',1,'org::hibernate::test::mappingexception']]],
  ['mappingnotfoundexception',['MappingNotFoundException',['../classorg_1_1hibernate_1_1_mapping_not_found_exception.html',1,'org::hibernate']]],
  ['mappingnotfoundexception',['MappingNotFoundException',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1_mapping_not_found_exception.html',1,'org::hibernate::metamodel::source']]],
  ['mappingreader',['MappingReader',['../classorg_1_1hibernate_1_1internal_1_1util_1_1xml_1_1_mapping_reader.html',1,'org::hibernate::internal::util::xml']]],
  ['mappings',['Mappings',['../interfaceorg_1_1hibernate_1_1cfg_1_1_mappings.html',1,'org::hibernate::cfg']]],
  ['mappingsimpl',['MappingsImpl',['../classorg_1_1hibernate_1_1cfg_1_1_configuration_1_1_mappings_impl.html',1,'org::hibernate::cfg::Configuration']]],
  ['mappingtools',['MappingTools',['../classorg_1_1hibernate_1_1envers_1_1tools_1_1_mapping_tools.html',1,'org::hibernate::envers::tools']]],
  ['mapproxy',['MapProxy',['../classorg_1_1hibernate_1_1proxy_1_1map_1_1_map_proxy.html',1,'org::hibernate::proxy::map']]],
  ['mapproxy_3c_20k_2c_20v_20_3e',['MapProxy&lt; K, V &gt;',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1lazy_1_1proxy_1_1_map_proxy_3_01_k_00_01_v_01_4.html',1,'org::hibernate::envers::entities::mapper::relation::lazy::proxy']]],
  ['mapproxyfactory',['MapProxyFactory',['../classorg_1_1hibernate_1_1proxy_1_1map_1_1_map_proxy_factory.html',1,'org::hibernate::proxy::map']]],
  ['mapsidtest',['MapsIdTest',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1annotations_1_1entity_1_1_maps_id_test.html',1,'org::hibernate::metamodel::source::annotations::entity']]],
  ['maptest',['MapTest',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_map_test.html',1,'org::hibernate::test::legacy']]],
  ['maptype',['MapType',['../classorg_1_1hibernate_1_1type_1_1_map_type.html',1,'org::hibernate::type']]],
  ['mapunientity',['MapUniEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1manytomany_1_1unidirectional_1_1_map_uni_entity.html',1,'org::hibernate::envers::test::entities::manytomany::unidirectional']]],
  ['mapvaluenode',['MapValueNode',['../classorg_1_1hibernate_1_1hql_1_1internal_1_1ast_1_1tree_1_1_map_value_node.html',1,'org::hibernate::hql::internal::ast::tree']]],
  ['mark',['Mark',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1query_1_1_mark.html',1,'org::hibernate::test::annotations::query']]],
  ['markerobject',['MarkerObject',['../classorg_1_1hibernate_1_1internal_1_1util_1_1_marker_object.html',1,'org::hibernate::internal::util']]],
  ['master',['Master',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_master.html',1,'org::hibernate::test::legacy']]],
  ['master',['Master',['../classorg_1_1hibernate_1_1test_1_1formulajoin_1_1_master.html',1,'org::hibernate::test::formulajoin']]],
  ['master',['Master',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1manytomany_1_1inverse_to_superclass_1_1_master.html',1,'org::hibernate::envers::test::integration::manytomany::inverseToSuperclass']]],
  ['master',['Master',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1onetomany_1_1inverse_to_superclass_1_1_master.html',1,'org::hibernate::envers::test::integration::onetomany::inverseToSuperclass']]],
  ['masterdetailtest',['MasterDetailTest',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_master_detail_test.html',1,'org::hibernate::test::legacy']]],
  ['match',['Match',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1reflection_1_1_match.html',1,'org::hibernate::test::annotations::reflection']]],
  ['matcher_3c_20t_20_3e',['Matcher&lt; T &gt;',['../interfaceorg_1_1hamcrest_1_1_matcher_3_01_t_01_4.html',1,'org::hamcrest']]],
  ['matchertest',['MatcherTest',['../classorg_1_1junit_1_1tests_1_1experimental_1_1_matcher_test.html',1,'org::junit::tests::experimental']]],
  ['matchmode',['MatchMode',['../enumorg_1_1hibernate_1_1criterion_1_1_match_mode.html',1,'org::hibernate::criterion']]],
  ['materializedblobentity',['MaterializedBlobEntity',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1lob_1_1_materialized_blob_entity.html',1,'org::hibernate::test::annotations::lob']]],
  ['materializedblobtest',['MaterializedBlobTest',['../classorg_1_1hibernate_1_1test_1_1lob_1_1_materialized_blob_test.html',1,'org::hibernate::test::lob']]],
  ['materializedblobtest',['MaterializedBlobTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1lob_1_1_materialized_blob_test.html',1,'org::hibernate::test::annotations::lob']]],
  ['materializedblobtype',['MaterializedBlobType',['../classorg_1_1hibernate_1_1type_1_1_materialized_blob_type.html',1,'org::hibernate::type']]],
  ['materializedclobtest',['MaterializedClobTest',['../classorg_1_1hibernate_1_1test_1_1lob_1_1_materialized_clob_test.html',1,'org::hibernate::test::lob']]],
  ['materializedclobtype',['MaterializedClobType',['../classorg_1_1hibernate_1_1type_1_1_materialized_clob_type.html',1,'org::hibernate::type']]],
  ['math',['Math',['../classorg_1_1h2_1_1java_1_1lang_1_1_math.html',1,'org::h2::java::lang']]],
  ['mathutils',['MathUtils',['../classorg_1_1h2_1_1util_1_1_math_utils.html',1,'org::h2::util']]],
  ['matrix',['Matrix',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1collectionelement_1_1_matrix.html',1,'org::hibernate::test::annotations::collectionelement']]],
  ['matrixdotgradleprofile',['MatrixDotGradleProfile',['../classorg_1_1hibernate_1_1build_1_1gradle_1_1testing_1_1database_1_1_matrix_dot_gradle_profile.html',1,'org::hibernate::build::gradle::testing::database']]],
  ['matrixnode',['MatrixNode',['../classorg_1_1hibernate_1_1build_1_1gradle_1_1testing_1_1matrix_1_1_matrix_node.html',1,'org::hibernate::build::gradle::testing::matrix']]],
  ['maximalizepropertyquery',['MaximalizePropertyQuery',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1query_1_1_maximalize_property_query.html',1,'org::hibernate::envers::test::integration::query']]],
  ['maxstartertest',['MaxStarterTest',['../classorg_1_1junit_1_1tests_1_1experimental_1_1max_1_1_max_starter_test.html',1,'org::junit::tests::experimental::max']]],
  ['mckoicasefragment',['MckoiCaseFragment',['../classorg_1_1hibernate_1_1sql_1_1_mckoi_case_fragment.html',1,'org::hibernate::sql']]],
  ['mckoidialect',['MckoiDialect',['../classorg_1_1hibernate_1_1dialect_1_1_mckoi_dialect.html',1,'org::hibernate::dialect']]],
  ['medicalhistory',['MedicalHistory',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1derivedidentities_1_1e4_1_1a_1_1_medical_history.html',1,'org::hibernate::test::annotations::derivedidentities::e4::a']]],
  ['medicalhistory',['MedicalHistory',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1derivedidentities_1_1e4_1_1b_1_1_medical_history.html',1,'org::hibernate::test::annotations::derivedidentities::e4::b']]],
  ['medicalhistory',['MedicalHistory',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1derivedidentities_1_1e5_1_1a_1_1_medical_history.html',1,'org::hibernate::test::annotations::derivedidentities::e5::a']]],
  ['medicalhistory',['MedicalHistory',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1derivedidentities_1_1e5_1_1b_1_1_medical_history.html',1,'org::hibernate::test::annotations::derivedidentities::e5::b']]],
  ['medicalhistory',['MedicalHistory',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1derivedidentities_1_1e5_1_1c_1_1_medical_history.html',1,'org::hibernate::test::annotations::derivedidentities::e5::c']]],
  ['medicalhistory',['MedicalHistory',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1derivedidentities_1_1e6_1_1a_1_1_medical_history.html',1,'org::hibernate::test::annotations::derivedidentities::e6::a']]],
  ['medicalhistory',['MedicalHistory',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1derivedidentities_1_1e6_1_1b_1_1_medical_history.html',1,'org::hibernate::test::annotations::derivedidentities::e6::b']]],
  ['medicalhistory',['MedicalHistory',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1derivedidentities_1_1_medical_history.html',1,'org::hibernate::test::annotations::derivedidentities']]],
  ['medication',['Medication',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_medication.html',1,'org::hibernate::test::legacy']]],
  ['memberofpredicate_3c_20e_2c_20c_20extends_20collection_3c_20e_20_3e_20_3e',['MemberOfPredicate&lt; E, C extends Collection&lt; E &gt; &gt;',['../classorg_1_1hibernate_1_1ejb_1_1criteria_1_1predicate_1_1_member_of_predicate_3_01_e_00_01_c_01e031a1a212bcddc6da5dca867a98a9e03.html',1,'org::hibernate::ejb::criteria::predicate']]],
  ['membership',['Membership',['../classorg_1_1hibernate_1_1test_1_1insertordering_1_1_membership.html',1,'org::hibernate::test::insertordering']]],
  ['membership',['Membership',['../classorg_1_1hibernate_1_1test_1_1sql_1_1autodiscovery_1_1_membership.html',1,'org::hibernate::test::sql::autodiscovery']]],
  ['membership',['Membership',['../classorg_1_1hibernate_1_1test_1_1manytomanyassociationclass_1_1_membership.html',1,'org::hibernate::test::manytomanyassociationclass']]],
  ['membershipwithcompositeid',['MembershipWithCompositeId',['../classorg_1_1hibernate_1_1test_1_1manytomanyassociationclass_1_1compositeid_1_1_membership_with_composite_id.html',1,'org::hibernate::test::manytomanyassociationclass::compositeid']]],
  ['memorycache',['MemoryCache',['../class_agent_provider_1_1_implementation_1_1_database_1_1_memory_cache.html',1,'AgentProvider::Implementation::Database']]],
  ['memoryfootprint',['MemoryFootprint',['../classorg_1_1h2_1_1test_1_1utils_1_1_memory_footprint.html',1,'org::h2::test::utils']]],
  ['menu',['Menu',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoonewithformula_1_1_menu.html',1,'org::hibernate::test::annotations::manytoonewithformula']]],
  ['merge',['Merge',['../classorg_1_1h2_1_1command_1_1dml_1_1_merge.html',1,'org::h2::command::dml']]],
  ['mergedocs',['MergeDocs',['../classorg_1_1h2_1_1build_1_1doc_1_1_merge_docs.html',1,'org::h2::build::doc']]],
  ['mergeevent',['MergeEvent',['../classorg_1_1hibernate_1_1event_1_1spi_1_1_merge_event.html',1,'org::hibernate::event::spi']]],
  ['mergeeventlistener',['MergeEventListener',['../interfaceorg_1_1hibernate_1_1event_1_1spi_1_1_merge_event_listener.html',1,'org::hibernate::event::spi']]],
  ['mergenewtest',['MergeNewTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1ops_1_1_merge_new_test.html',1,'org::hibernate::ejb::test::ops']]],
  ['mergetest',['MergeTest',['../classorg_1_1hibernate_1_1test_1_1nonflushedchanges_1_1_merge_test.html',1,'org::hibernate::test::nonflushedchanges']]],
  ['mergetest',['MergeTest',['../classorg_1_1hibernate_1_1test_1_1ops_1_1_merge_test.html',1,'org::hibernate::test::ops']]],
  ['mergetest',['MergeTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1emops_1_1_merge_test.html',1,'org::hibernate::ejb::test::emops']]],
  ['mergetest',['MergeTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1ops_1_1_merge_test.html',1,'org::hibernate::ejb::test::ops']]],
  ['message',['Message',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoonewithformula_1_1_message.html',1,'org::hibernate::test::annotations::manytoonewithformula']]],
  ['message',['Message',['../classorg_1_1h2_1_1jaqu_1_1util_1_1_message.html',1,'org::h2::jaqu::util']]],
  ['messagechannel',['MessageChannel',['../enum_network_adapter_1_1_interface_1_1_message_channel.html',1,'NetworkAdapter::Interface']]],
  ['messagehelper',['MessageHelper',['../classorg_1_1hibernate_1_1pretty_1_1_message_helper.html',1,'org::hibernate::pretty']]],
  ['messagetype',['MessageType',['../enum_environment_plugin_a_p_i_1_1_custom_network_messages_1_1_message_type.html',1,'EnvironmentPluginAPI::CustomNetworkMessages']]],
  ['metaattributable',['MetaAttributable',['../interfaceorg_1_1hibernate_1_1mapping_1_1_meta_attributable.html',1,'org::hibernate::mapping']]],
  ['metaattribute',['MetaAttribute',['../classorg_1_1hibernate_1_1mapping_1_1_meta_attribute.html',1,'org::hibernate::mapping']]],
  ['metaattribute',['MetaAttribute',['../classorg_1_1hibernate_1_1metamodel_1_1binding_1_1_meta_attribute.html',1,'org::hibernate::metamodel::binding']]],
  ['metaattributecontainer',['MetaAttributeContainer',['../interfaceorg_1_1hibernate_1_1internal_1_1jaxb_1_1mapping_1_1hbm_1_1_meta_attribute_container.html',1,'org::hibernate::internal::jaxb::mapping::hbm']]],
  ['metaattributecontext',['MetaAttributeContext',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1_meta_attribute_context.html',1,'org::hibernate::metamodel::source']]],
  ['metaattributesource',['MetaAttributeSource',['../interfaceorg_1_1hibernate_1_1metamodel_1_1source_1_1binder_1_1_meta_attribute_source.html',1,'org::hibernate::metamodel::source::binder']]],
  ['metacursor',['MetaCursor',['../classorg_1_1h2_1_1index_1_1_meta_cursor.html',1,'org::h2::index']]],
  ['metadata',['Metadata',['../interfaceorg_1_1hibernate_1_1metamodel_1_1_metadata.html',1,'org::hibernate::metamodel']]],
  ['metadatabuilder',['MetadataBuilder',['../interfaceorg_1_1hibernate_1_1metamodel_1_1_metadata_builder.html',1,'org::hibernate::metamodel']]],
  ['metadatabuilderimpl',['MetadataBuilderImpl',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1internal_1_1_metadata_builder_impl.html',1,'org::hibernate::metamodel::source::internal']]],
  ['metadataimpl',['MetadataImpl',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1internal_1_1_metadata_impl.html',1,'org::hibernate::metamodel::source::internal']]],
  ['metadataimplementor',['MetadataImplementor',['../interfaceorg_1_1hibernate_1_1metamodel_1_1source_1_1_metadata_implementor.html',1,'org::hibernate::metamodel::source']]],
  ['metadataimpltest',['MetadataImplTest',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1internal_1_1_metadata_impl_test.html',1,'org::hibernate::metamodel::source::internal']]],
  ['metadatasource',['MetadataSource',['../enumorg_1_1hibernate_1_1mapping_1_1_metadata_source.html',1,'org::hibernate::mapping']]],
  ['metadatasourceprocessingorder',['MetadataSourceProcessingOrder',['../enumorg_1_1hibernate_1_1metamodel_1_1_metadata_source_processing_order.html',1,'org::hibernate::metamodel']]],
  ['metadatasourceprocessor',['MetadataSourceProcessor',['../interfaceorg_1_1hibernate_1_1metamodel_1_1source_1_1_metadata_source_processor.html',1,'org::hibernate::metamodel::source']]],
  ['metadatasourcequeue',['MetadataSourceQueue',['../classorg_1_1hibernate_1_1cfg_1_1_configuration_1_1_metadata_source_queue.html',1,'org::hibernate::cfg::Configuration']]],
  ['metadatasources',['MetadataSources',['../classorg_1_1hibernate_1_1metamodel_1_1_metadata_sources.html',1,'org::hibernate::metamodel']]],
  ['metadatasourcetype',['MetadataSourceType',['../enumorg_1_1hibernate_1_1cfg_1_1_metadata_source_type.html',1,'org::hibernate::cfg']]],
  ['metadatatest',['MetadataTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1metadata_1_1_metadata_test.html',1,'org::hibernate::ejb::test::metadata']]],
  ['metadatatools',['MetadataTools',['../classorg_1_1hibernate_1_1envers_1_1configuration_1_1metadata_1_1_metadata_tools.html',1,'org::hibernate::envers::configuration::metadata']]],
  ['metaindex',['MetaIndex',['../classorg_1_1h2_1_1index_1_1_meta_index.html',1,'org::h2::index']]],
  ['metamodelimpl',['MetamodelImpl',['../classorg_1_1hibernate_1_1ejb_1_1metamodel_1_1_metamodel_impl.html',1,'org::hibernate::ejb::metamodel']]],
  ['metarecord',['MetaRecord',['../classorg_1_1h2_1_1engine_1_1_meta_record.html',1,'org::h2::engine']]],
  ['metatable',['MetaTable',['../classorg_1_1h2_1_1table_1_1_meta_table.html',1,'org::h2::table']]],
  ['metatype',['MetaType',['../classorg_1_1hibernate_1_1type_1_1_meta_type.html',1,'org::hibernate::type']]],
  ['metavalue',['MetaValue',['../interfaceorg_1_1hibernate_1_1annotations_1_1_meta_value.html',1,'org::hibernate::annotations']]],
  ['methodcall',['MethodCall',['../classorg_1_1junit_1_1tests_1_1experimental_1_1theories_1_1extendingwithstubs_1_1_method_call.html',1,'org::junit::tests::experimental::theories::extendingwithstubs']]],
  ['methodnode',['MethodNode',['../classorg_1_1hibernate_1_1hql_1_1internal_1_1ast_1_1tree_1_1_method_node.html',1,'org::hibernate::hql::internal::ast::tree']]],
  ['methodrulestest',['MethodRulesTest',['../classorg_1_1junit_1_1tests_1_1experimental_1_1rules_1_1_method_rules_test.html',1,'org::junit::tests::experimental::rules']]],
  ['middle',['Middle',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_middle.html',1,'org::hibernate::test::legacy']]],
  ['middle',['Middle',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1cascade_1_1multilevel_1_1_middle.html',1,'org::hibernate::ejb::test::cascade::multilevel']]],
  ['middlecomponentdata',['MiddleComponentData',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1_middle_component_data.html',1,'org::hibernate::envers::entities::mapper::relation']]],
  ['middlecomponentmapper',['MiddleComponentMapper',['../interfaceorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1component_1_1_middle_component_mapper.html',1,'org::hibernate::envers::entities::mapper::relation::component']]],
  ['middledummycomponentmapper',['MiddleDummyComponentMapper',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1component_1_1_middle_dummy_component_mapper.html',1,'org::hibernate::envers::entities::mapper::relation::component']]],
  ['middleiddata',['MiddleIdData',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1_middle_id_data.html',1,'org::hibernate::envers::entities::mapper::relation']]],
  ['middlekey',['MiddleKey',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_middle_key.html',1,'org::hibernate::test::legacy']]],
  ['middlemapkeyidcomponentmapper',['MiddleMapKeyIdComponentMapper',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1component_1_1_middle_map_key_id_component_mapper.html',1,'org::hibernate::envers::entities::mapper::relation::component']]],
  ['middlemapkeypropertycomponentmapper',['MiddleMapKeyPropertyComponentMapper',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1component_1_1_middle_map_key_property_component_mapper.html',1,'org::hibernate::envers::entities::mapper::relation::component']]],
  ['middlerelatedcomponentmapper',['MiddleRelatedComponentMapper',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1component_1_1_middle_related_component_mapper.html',1,'org::hibernate::envers::entities::mapper::relation::component']]],
  ['middlesimplecomponentmapper',['MiddleSimpleComponentMapper',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1component_1_1_middle_simple_component_mapper.html',1,'org::hibernate::envers::entities::mapper::relation::component']]],
  ['middlestraightcomponentmapper',['MiddleStraightComponentMapper',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1relation_1_1component_1_1_middle_straight_component_mapper.html',1,'org::hibernate::envers::entities::mapper::relation::component']]],
  ['migrate',['Migrate',['../classorg_1_1h2_1_1dev_1_1util_1_1_migrate.html',1,'org::h2::dev::util']]],
  ['migrationtest',['MigrationTest',['../classorg_1_1hibernate_1_1test_1_1schemaupdate_1_1_migration_test.html',1,'org::hibernate::test::schemaupdate']]],
  ['militarybuilding',['MilitaryBuilding',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1id_1_1sequences_1_1entities_1_1_military_building.html',1,'org::hibernate::test::annotations::id::sequences::entities']]],
  ['militarybuilding',['MilitaryBuilding',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1id_1_1entities_1_1_military_building.html',1,'org::hibernate::test::annotations::id::entities']]],
  ['millisdurationfield',['MillisDurationField',['../classorg_1_1joda_1_1time_1_1field_1_1_millis_duration_field.html',1,'org::joda::time::field']]],
  ['mimersqldialect',['MimerSQLDialect',['../classorg_1_1hibernate_1_1dialect_1_1_mimer_s_q_l_dialect.html',1,'org::hibernate::dialect']]],
  ['minimalsequenceentity',['MinimalSequenceEntity',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1id_1_1generationmappings_1_1_minimal_sequence_entity.html',1,'org::hibernate::test::annotations::id::generationmappings']]],
  ['minimaltableentity',['MinimalTableEntity',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1id_1_1generationmappings_1_1_minimal_table_entity.html',1,'org::hibernate::test::annotations::id::generationmappings']]],
  ['minmax',['MinMax',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1beanvalidation_1_1_min_max.html',1,'org::hibernate::test::annotations::beanvalidation']]],
  ['minutes',['Minutes',['../classorg_1_1joda_1_1time_1_1_minutes.html',1,'org::joda::time']]],
  ['mixedaccesstype',['MixedAccessType',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1accesstype_1_1_mixed_access_type.html',1,'org::hibernate::envers::test::integration::accesstype']]],
  ['mixedaccesstypeentity',['MixedAccessTypeEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1accesstype_1_1_mixed_access_type_entity.html',1,'org::hibernate::envers::test::integration::accesstype']]],
  ['mixedinheritancestrategiesentitytest',['MixedInheritanceStrategiesEntityTest',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1inheritance_1_1mixed_1_1_mixed_inheritance_strategies_entity_test.html',1,'org::hibernate::envers::test::integration::inheritance::mixed']]],
  ['mixedmode',['MixedMode',['../classorg_1_1h2_1_1samples_1_1_mixed_mode.html',1,'org::h2::samples']]],
  ['mixedoverrideentity',['MixedOverrideEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1superclass_1_1auditoverride_1_1_mixed_override_entity.html',1,'org::hibernate::envers::test::integration::superclass::auditoverride']]],
  ['mixedoverridetest',['MixedOverrideTest',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1superclass_1_1auditoverride_1_1_mixed_override_test.html',1,'org::hibernate::envers::test::integration::superclass::auditoverride']]],
  ['mixedtest',['MixedTest',['../classorg_1_1hibernate_1_1test_1_1mixed_1_1_mixed_test.html',1,'org::hibernate::test::mixed']]],
  ['mockhelper',['MockHelper',['../classorg_1_1hibernate_1_1metamodel_1_1source_1_1annotations_1_1xml_1_1mocker_1_1_mock_helper.html',1,'org::hibernate::metamodel::source::annotations::xml::mocker']]],
  ['mockpartial',['MockPartial',['../classorg_1_1joda_1_1time_1_1_mock_partial.html',1,'org::joda::time']]],
  ['mocks',['Mocks',['../classorg_1_1hibernate_1_1dialect_1_1_mocks.html',1,'org::hibernate::dialect']]],
  ['mockzeronullintegerconverter',['MockZeroNullIntegerConverter',['../classorg_1_1joda_1_1time_1_1convert_1_1_mock_zero_null_integer_converter.html',1,'org::joda::time::convert']]],
  ['mockzone',['MockZone',['../classorg_1_1joda_1_1time_1_1_mock_zone.html',1,'org::joda::time']]],
  ['mode',['Mode',['../classorg_1_1h2_1_1engine_1_1_mode.html',1,'org::h2::engine']]],
  ['model',['Model',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoonewithformula_1_1_model.html',1,'org::hibernate::test::annotations::manytoonewithformula']]],
  ['model',['Model',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1xml_1_1ejb3_1_1_model.html',1,'org::hibernate::test::annotations::xml::ejb3']]],
  ['model',['Model',['../classorg_1_1hibernate_1_1test_1_1batchfetch_1_1_model.html',1,'org::hibernate::test::batchfetch']]],
  ['model',['Model',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1onetomany_1_1_model.html',1,'org::hibernate::test::annotations::onetomany']]],
  ['modelid',['ModelId',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1manytoonewithformula_1_1_model_id.html',1,'org::hibernate::test::annotations::manytoonewithformula']]],
  ['modelstest',['ModelsTest',['../classorg_1_1h2_1_1test_1_1jaqu_1_1_models_test.html',1,'org::h2::test::jaqu']]],
  ['modelutils',['ModelUtils',['../classorg_1_1h2_1_1jaqu_1_1_model_utils.html',1,'org::h2::jaqu']]],
  ['modificationstore',['ModificationStore',['../enumorg_1_1hibernate_1_1envers_1_1_modification_store.html',1,'org::hibernate::envers']]],
  ['modifiedentitynames',['ModifiedEntityNames',['../interfaceorg_1_1hibernate_1_1envers_1_1_modified_entity_names.html',1,'org::hibernate::envers']]],
  ['modifiedentitynamesreader',['ModifiedEntityNamesReader',['../classorg_1_1hibernate_1_1envers_1_1revisioninfo_1_1_modified_entity_names_reader.html',1,'org::hibernate::envers::revisioninfo']]],
  ['modifiedentitytypeentity',['ModifiedEntityTypeEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1reventity_1_1trackmodifiedentities_1_1_modified_entity_type_entity.html',1,'org::hibernate::envers::test::entities::reventity::trackmodifiedentities']]],
  ['modifiedflagpropertyname',['ModifiedFlagPropertyName',['../classorg_1_1hibernate_1_1envers_1_1query_1_1property_1_1_modified_flag_property_name.html',1,'org::hibernate::envers::query::property']]],
  ['modifiedflagsuffix',['ModifiedFlagSuffix',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1modifiedflags_1_1_modified_flag_suffix.html',1,'org::hibernate::envers::test::integration::modifiedflags']]],
  ['modworkunit',['ModWorkUnit',['../classorg_1_1hibernate_1_1envers_1_1synchronization_1_1work_1_1_mod_work_unit.html',1,'org::hibernate::envers::synchronization::work']]],
  ['monetaryamount',['MonetaryAmount',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1embeddables_1_1nested_1_1_monetary_amount.html',1,'org::hibernate::test::annotations::embeddables::nested']]],
  ['monetaryamount',['MonetaryAmount',['../classorg_1_1hibernate_1_1test_1_1sql_1_1hand_1_1_monetary_amount.html',1,'org::hibernate::test::sql::hand']]],
  ['monetaryamount',['MonetaryAmount',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1entity_1_1_monetary_amount.html',1,'org::hibernate::test::annotations::entity']]],
  ['monetaryamountusertype',['MonetaryAmountUserType',['../classorg_1_1hibernate_1_1test_1_1sql_1_1hand_1_1_monetary_amount_user_type.html',1,'org::hibernate::test::sql::hand']]],
  ['monetaryamountusertype',['MonetaryAmountUserType',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1entity_1_1_monetary_amount_user_type.html',1,'org::hibernate::test::annotations::entity']]],
  ['monetoryamount',['MonetoryAmount',['../classorg_1_1hibernate_1_1test_1_1cut_1_1_monetory_amount.html',1,'org::hibernate::test::cut']]],
  ['monetoryamountusertype',['MonetoryAmountUserType',['../classorg_1_1hibernate_1_1test_1_1cut_1_1_monetory_amount_user_type.html',1,'org::hibernate::test::cut']]],
  ['money',['Money',['../classjunit_1_1samples_1_1money_1_1_money.html',1,'junit::samples::money']]],
  ['money',['Money',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1defaultpar_1_1_money.html',1,'org::hibernate::ejb::test::pack::defaultpar']]],
  ['money',['Money',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1war_1_1_money.html',1,'org::hibernate::ejb::test::pack::war']]],
  ['money1',['Money1',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1defaultpar__1__0_1_1_money1.html',1,'org::hibernate::ejb::test::pack::defaultpar_1_0']]],
  ['moneybag',['MoneyBag',['../classjunit_1_1samples_1_1money_1_1_money_bag.html',1,'junit::samples::money']]],
  ['moneytest',['MoneyTest',['../classorg_1_1junit_1_1samples_1_1money_1_1_money_test.html',1,'org::junit::samples::money']]],
  ['moneytest',['MoneyTest',['../classjunit_1_1samples_1_1money_1_1_money_test.html',1,'junit::samples::money']]],
  ['monkey',['Monkey',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1id_1_1entities_1_1_monkey.html',1,'org::hibernate::test::annotations::id::entities']]],
  ['monkey',['Monkey',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1id_1_1sequences_1_1entities_1_1_monkey.html',1,'org::hibernate::test::annotations::id::sequences::entities']]],
  ['monkey',['Monkey',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1onetomany_1_1_monkey.html',1,'org::hibernate::test::annotations::onetomany']]],
  ['mono',['Mono',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_mono.html',1,'org::hibernate::test::legacy']]],
  ['month',['Month',['../enumorg_1_1hibernate_1_1test_1_1annotations_1_1array_1_1_contest_1_1_month.html',1,'org::hibernate::test::annotations::array::Contest']]],
  ['monthday',['MonthDay',['../classorg_1_1joda_1_1time_1_1_month_day.html',1,'org::joda::time']]],
  ['months',['Months',['../classorg_1_1joda_1_1time_1_1_months.html',1,'org::joda::time']]],
  ['morecrazyidfieldnamestuffentity',['MoreCrazyIdFieldNameStuffEntity',['../classorg_1_1hibernate_1_1test_1_1hql_1_1_more_crazy_id_field_name_stuff_entity.html',1,'org::hibernate::test::hql']]],
  ['morefetchprofiletest',['MoreFetchProfileTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1fetchprofile_1_1_more_fetch_profile_test.html',1,'org::hibernate::test::annotations::fetchprofile']]],
  ['morestuff',['MoreStuff',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_more_stuff.html',1,'org::hibernate::test::legacy']]],
  ['morito',['Morito',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1cfgxmlpar_1_1_morito.html',1,'org::hibernate::ejb::test::pack::cfgxmlpar']]],
  ['mother',['Mother',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1engine_1_1collection_1_1_mother.html',1,'org::hibernate::test::annotations::engine::collection']]],
  ['mouse',['Mouse',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1war_1_1_mouse.html',1,'org::hibernate::ejb::test::pack::war']]],
  ['mouse',['Mouse',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1defaultpar_1_1_mouse.html',1,'org::hibernate::ejb::test::pack::defaultpar']]],
  ['mouse1',['Mouse1',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1pack_1_1defaultpar__1__0_1_1_mouse1.html',1,'org::hibernate::ejb::test::pack::defaultpar_1_0']]],
  ['mouth',['Mouth',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1cascade_1_1_mouth.html',1,'org::hibernate::test::annotations::cascade']]],
  ['move',['Move',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1override_1_1_move.html',1,'org::hibernate::test::annotations::override']]],
  ['movingthing',['MovingThing',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1polymorphism_1_1_moving_thing.html',1,'org::hibernate::test::annotations::polymorphism']]],
  ['mulid',['MulId',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1ids_1_1_mul_id.html',1,'org::hibernate::envers::test::entities::ids']]],
  ['mulidbidirectional',['MulIdBidirectional',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1onetoone_1_1bidirectional_1_1ids_1_1_mul_id_bidirectional.html',1,'org::hibernate::envers::test::integration::onetoone::bidirectional::ids']]],
  ['mulidnaming',['MulIdNaming',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1naming_1_1ids_1_1_mul_id_naming.html',1,'org::hibernate::envers::test::integration::naming::ids']]],
  ['mulidonetomanyquery',['MulIdOneToManyQuery',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1query_1_1ids_1_1_mul_id_one_to_many_query.html',1,'org::hibernate::envers::test::integration::query::ids']]],
  ['mulidsecondary',['MulIdSecondary',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1secondary_1_1ids_1_1_mul_id_secondary.html',1,'org::hibernate::envers::test::integration::secondary::ids']]],
  ['mulidtestentity',['MulIdTestEntity',['../classorg_1_1hibernate_1_1envers_1_1test_1_1entities_1_1ids_1_1_mul_id_test_entity.html',1,'org::hibernate::envers::test::entities::ids']]],
  ['multi',['Multi',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_multi.html',1,'org::hibernate::test::legacy']]],
  ['multicirclejpacascadeidentitytest',['MultiCircleJpaCascadeIdentityTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1cascade_1_1multicircle_1_1jpa_1_1identity_1_1_mu72264c4a042eea9191af5fe9e8da1bd2.html',1,'org::hibernate::test::annotations::cascade::multicircle::jpa::identity']]],
  ['multicirclejpacascadesequencetest',['MultiCircleJpaCascadeSequenceTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1cascade_1_1multicircle_1_1jpa_1_1sequence_1_1_mu1e854febb5f68471d5b260ede13c7311.html',1,'org::hibernate::test::annotations::cascade::multicircle::jpa::sequence']]],
  ['multicirclejpacascadetest',['MultiCircleJpaCascadeTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1cascade_1_1multicircle_1_1_multi_circle_jpa_cascade_test.html',1,'org::hibernate::ejb::test::cascade::multicircle']]],
  ['multicirclenonjpacascadeidentitytest',['MultiCircleNonJpaCascadeIdentityTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1cascade_1_1multicircle_1_1nonjpa_1_1identity_1_16a3687f253229cbfa9ad0d93492a6170.html',1,'org::hibernate::test::annotations::cascade::multicircle::nonjpa::identity']]],
  ['multicirclenonjpacascadesequencetest',['MultiCircleNonJpaCascadeSequenceTest',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1cascade_1_1multicircle_1_1nonjpa_1_1sequence_1_1e0e08478a3ea63f769ed06fc4c588484.html',1,'org::hibernate::test::annotations::cascade::multicircle::nonjpa::sequence']]],
  ['multidimension',['MultiDimension',['../classorg_1_1h2_1_1tools_1_1_multi_dimension.html',1,'org::h2::tools']]],
  ['multilevelcascadetest',['MultiLevelCascadeTest',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1cascade_1_1multilevel_1_1_multi_level_cascade_test.html',1,'org::hibernate::ejb::test::cascade::multilevel']]],
  ['multilineimportfiletest',['MultiLineImportFileTest',['../classorg_1_1hibernate_1_1test_1_1fileimport_1_1_multi_line_import_file_test.html',1,'org::hibernate::test::fileimport']]],
  ['multipathcascadetest',['MultiPathCascadeTest',['../classorg_1_1hibernate_1_1test_1_1cascade_1_1_multi_path_cascade_test.html',1,'org::hibernate::test::cascade']]],
  ['multipathcirclecascadechecknullfalsedelayedinserttest',['MultiPathCircleCascadeCheckNullFalseDelayedInsertTest',['../classorg_1_1hibernate_1_1test_1_1cascade_1_1circle_1_1_multi_path_circle_cascade_check_null_false_delayed_insert_test.html',1,'org::hibernate::test::cascade::circle']]],
  ['multipathcirclecascadechecknullibilityfalsetest',['MultiPathCircleCascadeCheckNullibilityFalseTest',['../classorg_1_1hibernate_1_1test_1_1cascade_1_1circle_1_1_multi_path_circle_cascade_check_nullibility_false_test.html',1,'org::hibernate::test::cascade::circle']]],
  ['multipathcirclecascadechecknullibilitytruetest',['MultiPathCircleCascadeCheckNullibilityTrueTest',['../classorg_1_1hibernate_1_1test_1_1cascade_1_1circle_1_1_multi_path_circle_cascade_check_nullibility_true_test.html',1,'org::hibernate::test::cascade::circle']]],
  ['multipathcirclecascadechecknulltruedelayedinserttest',['MultiPathCircleCascadeCheckNullTrueDelayedInsertTest',['../classorg_1_1hibernate_1_1test_1_1cascade_1_1circle_1_1_multi_path_circle_cascade_check_null_true_delayed_insert_test.html',1,'org::hibernate::test::cascade::circle']]],
  ['multipathcirclecascadedelayedinserttest',['MultiPathCircleCascadeDelayedInsertTest',['../classorg_1_1hibernate_1_1test_1_1cascade_1_1circle_1_1_multi_path_circle_cascade_delayed_insert_test.html',1,'org::hibernate::test::cascade::circle']]],
  ['multipathcirclecascadetest',['MultiPathCircleCascadeTest',['../classorg_1_1hibernate_1_1test_1_1cascade_1_1circle_1_1_multi_path_circle_cascade_test.html',1,'org::hibernate::test::cascade::circle']]],
  ['multiple',['Multiple',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1idclassgeneratedvalue_1_1_multiple.html',1,'org::hibernate::test::annotations::idclassgeneratedvalue']]],
  ['multipleassociationstest',['MultipleAssociationsTest',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1multiplerelations_1_1_multiple_associations_test.html',1,'org::hibernate::envers::test::integration::multiplerelations']]],
  ['multipleauditparentstest',['MultipleAuditParentsTest',['../classorg_1_1hibernate_1_1envers_1_1test_1_1integration_1_1superclass_1_1auditparents_1_1_multiple_audit_parents_test.html',1,'org::hibernate::envers::test::integration::superclass::auditparents']]],
  ['multiplebagfetchexception',['MultipleBagFetchException',['../classorg_1_1hibernate_1_1loader_1_1_multiple_bag_fetch_exception.html',1,'org::hibernate::loader']]],
  ['multiplefailureexceptiontest',['MultipleFailureExceptionTest',['../classorg_1_1junit_1_1tests_1_1assertion_1_1_multiple_failure_exception_test.html',1,'org::junit::tests::assertion']]],
  ['multiplehilopertablegenerator',['MultipleHiLoPerTableGenerator',['../classorg_1_1hibernate_1_1id_1_1_multiple_hi_lo_per_table_generator.html',1,'org::hibernate::id']]],
  ['multiplehilopertablegeneratortest',['MultipleHiLoPerTableGeneratorTest',['../classorg_1_1hibernate_1_1test_1_1id_1_1_multiple_hi_lo_per_table_generator_test.html',1,'org::hibernate::test::id']]],
  ['multipleidmapper',['MultipleIdMapper',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1id_1_1_multiple_id_mapper.html',1,'org::hibernate::envers::entities::mapper::id']]],
  ['multiplelinessqlcommandextractor',['MultipleLinesSqlCommandExtractor',['../classorg_1_1hibernate_1_1tool_1_1hbm2ddl_1_1_multiple_lines_sql_command_extractor.html',1,'org::hibernate::tool::hbm2ddl']]],
  ['multiplepk',['MultiplePK',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1idclassgeneratedvalue_1_1_multiple_p_k.html',1,'org::hibernate::test::annotations::idclassgeneratedvalue']]],
  ['multiplicity',['Multiplicity',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_multiplicity.html',1,'org::hibernate::test::legacy']]],
  ['multiplicitytype',['MultiplicityType',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_multiplicity_type.html',1,'org::hibernate::test::legacy']]],
  ['multipropertymapper',['MultiPropertyMapper',['../classorg_1_1hibernate_1_1envers_1_1entities_1_1mapper_1_1_multi_property_mapper.html',1,'org::hibernate::envers::entities::mapper']]],
  ['multitabledeleteexecutor',['MultiTableDeleteExecutor',['../classorg_1_1hibernate_1_1hql_1_1internal_1_1ast_1_1exec_1_1_multi_table_delete_executor.html',1,'org::hibernate::hql::internal::ast::exec']]],
  ['multitabletest',['MultiTableTest',['../classorg_1_1hibernate_1_1test_1_1legacy_1_1_multi_table_test.html',1,'org::hibernate::test::legacy']]],
  ['multitableupdateexecutor',['MultiTableUpdateExecutor',['../classorg_1_1hibernate_1_1hql_1_1internal_1_1ast_1_1exec_1_1_multi_table_update_executor.html',1,'org::hibernate::hql::internal::ast::exec']]],
  ['multitenancystrategy',['MultiTenancyStrategy',['../enumorg_1_1hibernate_1_1_multi_tenancy_strategy.html',1,'org::hibernate']]],
  ['multitenantconnectionprovider',['MultiTenantConnectionProvider',['../interfaceorg_1_1hibernate_1_1service_1_1jdbc_1_1connections_1_1spi_1_1_multi_tenant_connection_provider.html',1,'org::hibernate::service::jdbc::connections::spi']]],
  ['multitenantconnectionproviderimpl',['MultiTenantConnectionProviderImpl',['../class_multi_tenant_connection_provider_impl.html',1,'']]],
  ['multitenantconnectionproviderinitiator',['MultiTenantConnectionProviderInitiator',['../classorg_1_1hibernate_1_1service_1_1jdbc_1_1connections_1_1internal_1_1_multi_tenant_connection_provider_initiator.html',1,'org::hibernate::service::jdbc::connections::internal']]],
  ['multitypedbasicattributesentity',['MultiTypedBasicAttributesEntity',['../classorg_1_1hibernate_1_1ejb_1_1criteria_1_1_multi_typed_basic_attributes_entity.html',1,'org::hibernate::ejb::criteria']]],
  ['multiversioncursor',['MultiVersionCursor',['../classorg_1_1h2_1_1index_1_1_multi_version_cursor.html',1,'org::h2::index']]],
  ['multiversionindex',['MultiVersionIndex',['../classorg_1_1h2_1_1index_1_1_multi_version_index.html',1,'org::h2::index']]],
  ['music',['Music',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1beanvalidation_1_1_music.html',1,'org::hibernate::test::annotations::beanvalidation']]],
  ['music',['Music',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1exception_1_1_music.html',1,'org::hibernate::ejb::test::exception']]],
  ['music',['Music',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1inheritance_1_1singletable_1_1_music.html',1,'org::hibernate::test::annotations::inheritance::singletable']]],
  ['music',['Music',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1emops_1_1_music.html',1,'org::hibernate::ejb::test::emops']]],
  ['musician',['Musician',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1exception_1_1_musician.html',1,'org::hibernate::ejb::test::exception']]],
  ['mutabilityplan_3c_20t_20_3e',['MutabilityPlan&lt; T &gt;',['../interfaceorg_1_1hibernate_1_1type_1_1descriptor_1_1java_1_1_mutability_plan_3_01_t_01_4.html',1,'org::hibernate::type::descriptor::java']]],
  ['mutableboolean',['MutableBoolean',['../classorg_1_1hibernate_1_1envers_1_1tools_1_1_mutable_boolean.html',1,'org::hibernate::envers::tools']]],
  ['mutabledatetime',['MutableDateTime',['../classorg_1_1joda_1_1time_1_1_mutable_date_time.html',1,'org::joda::time']]],
  ['mutableidentifiergeneratorfactory',['MutableIdentifierGeneratorFactory',['../interfaceorg_1_1hibernate_1_1id_1_1factory_1_1spi_1_1_mutable_identifier_generator_factory.html',1,'org::hibernate::id::factory::spi']]],
  ['mutableidentifiergeneratorfactoryinitiator',['MutableIdentifierGeneratorFactoryInitiator',['../classorg_1_1hibernate_1_1id_1_1factory_1_1internal_1_1_mutable_identifier_generator_factory_initiator.html',1,'org::hibernate::id::factory::internal']]],
  ['mutableinteger',['MutableInteger',['../classorg_1_1hibernate_1_1envers_1_1tools_1_1_mutable_integer.html',1,'org::hibernate::envers::tools']]],
  ['mutableinterval',['MutableInterval',['../classorg_1_1joda_1_1time_1_1_mutable_interval.html',1,'org::joda::time']]],
  ['mutablemutabilityplan_3c_20t_20_3e',['MutableMutabilityPlan&lt; T &gt;',['../classorg_1_1hibernate_1_1type_1_1descriptor_1_1java_1_1_mutable_mutability_plan_3_01_t_01_4.html',1,'org::hibernate::type::descriptor::java']]],
  ['mutablenaturalidtest',['MutableNaturalIdTest',['../classorg_1_1hibernate_1_1test_1_1naturalid_1_1mutable_1_1_mutable_natural_id_test.html',1,'org::hibernate::test::naturalid::mutable']]],
  ['mutablenaturalidtest',['MutableNaturalIdTest',['../classorg_1_1hibernate_1_1test_1_1jpa_1_1naturalid_1_1_mutable_natural_id_test.html',1,'org::hibernate::test::jpa::naturalid']]],
  ['mutableperiod',['MutablePeriod',['../classorg_1_1joda_1_1time_1_1_mutable_period.html',1,'org::joda::time']]],
  ['mutabletype',['MutableType',['../classorg_1_1hibernate_1_1type_1_1_mutable_type.html',1,'org::hibernate::type']]],
  ['mutualfund',['MutualFund',['../classorg_1_1hibernate_1_1test_1_1cut_1_1_mutual_fund.html',1,'org::hibernate::test::cut']]],
  ['mychild',['MyChild',['../classorg_1_1hibernate_1_1test_1_1generatedkeys_1_1identity_1_1_my_child.html',1,'org::hibernate::test::generatedkeys::identity']]],
  ['myentity',['MyEntity',['../classorg_1_1hibernate_1_1test_1_1generatedkeys_1_1seqidentity_1_1_my_entity.html',1,'org::hibernate::test::generatedkeys::seqidentity']]],
  ['myentity',['MyEntity',['../classorg_1_1hibernate_1_1test_1_1generatedkeys_1_1identity_1_1_my_entity.html',1,'org::hibernate::test::generatedkeys::identity']]],
  ['myentity',['MyEntity',['../classorg_1_1hibernate_1_1test_1_1generatedkeys_1_1select_1_1_my_entity.html',1,'org::hibernate::test::generatedkeys::select']]],
  ['myentity',['MyEntity',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1quote_1_1resultsetmappings_1_1_my_entity.html',1,'org::hibernate::test::annotations::quote::resultsetmappings']]],
  ['myentity',['MyEntity',['../classorg_1_1hibernate_1_1test_1_1jpa_1_1_my_entity.html',1,'org::hibernate::test::jpa']]],
  ['myentityinstantiator',['MyEntityInstantiator',['../classorg_1_1hibernate_1_1test_1_1dynamicentity_1_1tuplizer2_1_1_my_entity_instantiator.html',1,'org::hibernate::test::dynamicentity::tuplizer2']]],
  ['myentityinstantiator',['MyEntityInstantiator',['../classorg_1_1hibernate_1_1test_1_1dynamicentity_1_1tuplizer_1_1_my_entity_instantiator.html',1,'org::hibernate::test::dynamicentity::tuplizer']]],
  ['myentitytuplizer',['MyEntityTuplizer',['../classorg_1_1hibernate_1_1test_1_1dynamicentity_1_1tuplizer2_1_1_my_entity_tuplizer.html',1,'org::hibernate::test::dynamicentity::tuplizer2']]],
  ['myentitytuplizer',['MyEntityTuplizer',['../classorg_1_1hibernate_1_1test_1_1dynamicentity_1_1tuplizer_1_1_my_entity_tuplizer.html',1,'org::hibernate::test::dynamicentity::tuplizer']]],
  ['myintegrator',['MyIntegrator',['../class_my_integrator.html',1,'']]],
  ['myinterface',['MyInterface',['../interfaceorg_1_1hibernate_1_1test_1_1abstractembeddedcomponents_1_1cid_1_1_my_interface.html',1,'org::hibernate::test::abstractembeddedcomponents::cid']]],
  ['myinterfaceimpl',['MyInterfaceImpl',['../classorg_1_1hibernate_1_1test_1_1abstractembeddedcomponents_1_1cid_1_1_my_interface_impl.html',1,'org::hibernate::test::abstractembeddedcomponents::cid']]],
  ['mylist_3c_20x_20_3e',['MyList&lt; X &gt;',['../classorg_1_1hibernate_1_1test_1_1collection_1_1custom_1_1basic_1_1_my_list_3_01_x_01_4.html',1,'org::hibernate::test::collection::custom::basic']]],
  ['mylistener',['MyListener',['../classorg_1_1junit_1_1tests_1_1listening_1_1_runner_test_1_1_my_listener.html',1,'org::junit::tests::listening::RunnerTest']]],
  ['mylisttype',['MyListType',['../classorg_1_1hibernate_1_1test_1_1collection_1_1custom_1_1basic_1_1_my_list_type.html',1,'org::hibernate::test::collection::custom::basic']]],
  ['mynamingstrategy',['MyNamingStrategy',['../classorg_1_1hibernate_1_1ejb_1_1test_1_1_my_naming_strategy.html',1,'org::hibernate::ejb::test']]],
  ['myoid',['MyOid',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1type_1_1_my_oid.html',1,'org::hibernate::test::annotations::type']]],
  ['myoidgenerator',['MyOidGenerator',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1type_1_1_my_oid_generator.html',1,'org::hibernate::test::annotations::type']]],
  ['myoidtype',['MyOidType',['../classorg_1_1hibernate_1_1test_1_1annotations_1_1type_1_1_my_oid_type.html',1,'org::hibernate::test::annotations::type']]],
  ['myownannotation',['MyOwnAnnotation',['../interfaceorg_1_1junit_1_1tests_1_1description_1_1_annotated_description_test_1_1_my_own_annotation.html',1,'org::junit::tests::description::AnnotatedDescriptionTest']]],
  ['mysibling',['MySibling',['../classorg_1_1hibernate_1_1test_1_1generatedkeys_1_1identity_1_1_my_sibling.html',1,'org::hibernate::test::generatedkeys::identity']]],
  ['mysql5dialect',['MySQL5Dialect',['../classorg_1_1hibernate_1_1dialect_1_1_my_s_q_l5_dialect.html',1,'org::hibernate::dialect']]],
  ['mysql5innodbdialect',['MySQL5InnoDBDialect',['../classorg_1_1hibernate_1_1dialect_1_1_my_s_q_l5_inno_d_b_dialect.html',1,'org::hibernate::dialect']]],
  ['mysqlcustomsqltest',['MySQLCustomSQLTest',['../classorg_1_1hibernate_1_1test_1_1sql_1_1hand_1_1custom_1_1mysql_1_1_my_s_q_l_custom_s_q_l_test.html',1,'org::hibernate::test::sql::hand::custom::mysql']]],
  ['mysqldialect',['MySQLDialect',['../classorg_1_1hibernate_1_1dialect_1_1_my_s_q_l_dialect.html',1,'org::hibernate::dialect']]],
  ['mysqlinnodbdialect',['MySQLInnoDBDialect',['../classorg_1_1hibernate_1_1dialect_1_1_my_s_q_l_inno_d_b_dialect.html',1,'org::hibernate::dialect']]],
  ['mysqlmyisamdialect',['MySQLMyISAMDialect',['../classorg_1_1hibernate_1_1dialect_1_1_my_s_q_l_my_i_s_a_m_dialect.html',1,'org::hibernate::dialect']]],
  ['mysqlroundfunctiontest',['MySQLRoundFunctionTest',['../classorg_1_1hibernate_1_1test_1_1dialect_1_1function_1_1_my_s_q_l_round_function_test.html',1,'org::hibernate::test::dialect::function']]],
  ['mysubclassentity',['MySubclassEntity',['../classorg_1_1hibernate_1_1test_1_1jpa_1_1_my_subclass_entity.html',1,'org::hibernate::test::jpa']]]
];
